/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GarageSearchPageDto } from '../../models/garage-search-page-dto';

export interface GarageSearchControllerForBrand$Params {

/**
 * The place the count is measured from, as "lat,lng" in Romania; rounded to three decimals. Without it, all of Romania
 */
  near?: string;

/**
 * The brand, by its catalogue id
 */
  brandId: string;

/**
 * The nextCursor of the previous page; opaque
 */
  cursor?: string;
}

export function garageSearchControllerForBrand(http: HttpClient, rootUrl: string, params: GarageSearchControllerForBrand$Params, context?: HttpContext): Observable<StrictHttpResponse<GarageSearchPageDto>> {
  const rb = new RequestBuilder(rootUrl, garageSearchControllerForBrand.PATH, 'get');
  if (params) {
    rb.query('near', params.near, {});
    rb.query('brandId', params.brandId, {});
    rb.query('cursor', params.cursor, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GarageSearchPageDto>;
    })
  );
}

garageSearchControllerForBrand.PATH = '/api/v1/search/garages';
