/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlacesResultDto } from '../../models/places-result-dto';

export interface PlacesControllerSearch$Params {

/**
 * What the owner typed, trimmed
 */
  q: string;
  lang?: 'ro' | 'en';
}

export function placesControllerSearch(http: HttpClient, rootUrl: string, params: PlacesControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<PlacesResultDto>> {
  const rb = new RequestBuilder(rootUrl, placesControllerSearch.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
    rb.query('lang', params.lang, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlacesResultDto>;
    })
  );
}

placesControllerSearch.PATH = '/api/v1/places';
