/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JobListDto } from '../../models/job-list-dto';

export interface GarageJobsControllerList$Params {

/**
 * The nextCursor of the previous page
 */
  cursor?: string;
}

export function garageJobsControllerList(http: HttpClient, rootUrl: string, params?: GarageJobsControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<JobListDto>> {
  const rb = new RequestBuilder(rootUrl, garageJobsControllerList.PATH, 'get');
  if (params) {
    rb.query('cursor', params.cursor, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JobListDto>;
    })
  );
}

garageJobsControllerList.PATH = '/api/v1/garage/jobs';
