/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JobStepDto } from '../../models/job-step-dto';
import { JobStepTextDto } from '../../models/job-step-text-dto';

export interface JobStepsControllerAdd$Params {
  id: string;

/**
 * One per step the person means; a repeat answers the first
 */
  'Idempotency-Key': string;
      body: JobStepTextDto
}

export function jobStepsControllerAdd(http: HttpClient, rootUrl: string, params: JobStepsControllerAdd$Params, context?: HttpContext): Observable<StrictHttpResponse<JobStepDto>> {
  const rb = new RequestBuilder(rootUrl, jobStepsControllerAdd.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JobStepDto>;
    })
  );
}

jobStepsControllerAdd.PATH = '/api/v1/garage/jobs/{id}/steps';
