/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JobStepDto } from '../../models/job-step-dto';
import { JobStepTextDto } from '../../models/job-step-text-dto';

export interface JobStepsControllerRename$Params {
  id: string;
  stepId: string;
      body: JobStepTextDto
}

export function jobStepsControllerRename(http: HttpClient, rootUrl: string, params: JobStepsControllerRename$Params, context?: HttpContext): Observable<StrictHttpResponse<JobStepDto>> {
  const rb = new RequestBuilder(rootUrl, jobStepsControllerRename.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('stepId', params.stepId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JobStepDto>;
    })
  );
}

jobStepsControllerRename.PATH = '/api/v1/garage/jobs/{id}/steps/{stepId}';
