/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentPageAddressDto } from '../../models/document-page-address-dto';

export interface LegalDocumentsControllerPageAddress$Params {
  id: string;
  documentId: string;
  n: string;
}

export function legalDocumentsControllerPageAddress(http: HttpClient, rootUrl: string, params: LegalDocumentsControllerPageAddress$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentPageAddressDto>> {
  const rb = new RequestBuilder(rootUrl, legalDocumentsControllerPageAddress.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('documentId', params.documentId, {});
    rb.path('n', params.n, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentPageAddressDto>;
    })
  );
}

legalDocumentsControllerPageAddress.PATH = '/api/v1/admin/verification-files/{id}/documents/{documentId}/pages/{n}/download-url';
