/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateQuoteRequestDto } from '../../models/create-quote-request-dto';
import { RequestDto } from '../../models/request-dto';

export interface QuoteRequestsControllerSend$Params {

/**
 * One per send the driver means; a repeat answers the first request
 */
  'Idempotency-Key': string;
      body: CreateQuoteRequestDto
}

export function quoteRequestsControllerSend(http: HttpClient, rootUrl: string, params: QuoteRequestsControllerSend$Params, context?: HttpContext): Observable<StrictHttpResponse<RequestDto>> {
  const rb = new RequestBuilder(rootUrl, quoteRequestsControllerSend.PATH, 'post');
  if (params) {
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RequestDto>;
    })
  );
}

quoteRequestsControllerSend.PATH = '/api/v1/quote-requests';
