/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CandidateGarageListDto } from '../../models/candidate-garage-list-dto';

export interface QuoteRequestsControllerCandidates$Params {

/**
 * The place the count is measured from, as "lat,lng" in Romania; rounded to three decimals. Without it, all of Romania
 */
  near?: string;
  carId: string;

/**
 * The jobs switched on, as comma-separated ids
 */
  jobTypeIds?: string;

/**
 * The profile's garage, already in the request
 */
  exclude?: string;
}

export function quoteRequestsControllerCandidates(http: HttpClient, rootUrl: string, params: QuoteRequestsControllerCandidates$Params, context?: HttpContext): Observable<StrictHttpResponse<CandidateGarageListDto>> {
  const rb = new RequestBuilder(rootUrl, quoteRequestsControllerCandidates.PATH, 'get');
  if (params) {
    rb.query('near', params.near, {});
    rb.query('carId', params.carId, {});
    rb.query('jobTypeIds', params.jobTypeIds, {});
    rb.query('exclude', params.exclude, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CandidateGarageListDto>;
    })
  );
}

quoteRequestsControllerCandidates.PATH = '/api/v1/quote-requests/garages';
