/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface PublicLiveControllerLive$Params {

/**
 * The garage a profile shows
 */
  garages?: string;

/**
 * The mechanic a profile shows
 */
  mechanics?: string;

/**
 * The brand whose search results are shown
 */
  brand?: string;
}

export function publicLiveControllerLive(http: HttpClient, rootUrl: string, params?: PublicLiveControllerLive$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, publicLiveControllerLive.PATH, 'get');
  if (params) {
    rb.query('garages', params.garages, {});
    rb.query('mechanics', params.mechanics, {});
    rb.query('brand', params.brand, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

publicLiveControllerLive.PATH = '/api/v1/live/public';
