/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GarageRequestListDto } from '../../models/garage-request-list-dto';

export interface GarageRequestsControllerList$Params {

/**
 * The nextCursor of the previous page
 */
  cursor?: string;

/**
 * waiting: the rows the garage can still answer; closed: the rows closed for it in the last 24 hours, one page; quoted: the rows the garage quoted whose quote still waits, newest quote first
 */
  status?: 'waiting' | 'closed' | 'quoted';
}

export function garageRequestsControllerList(http: HttpClient, rootUrl: string, params?: GarageRequestsControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<GarageRequestListDto>> {
  const rb = new RequestBuilder(rootUrl, garageRequestsControllerList.PATH, 'get');
  if (params) {
    rb.query('cursor', params.cursor, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GarageRequestListDto>;
    })
  );
}

garageRequestsControllerList.PATH = '/api/v1/garage/requests';
