/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GarageRequestDto } from '../../models/garage-request-dto';

export interface GarageRequestsControllerGet$Params {
  id: string;
}

export function garageRequestsControllerGet(http: HttpClient, rootUrl: string, params: GarageRequestsControllerGet$Params, context?: HttpContext): Observable<StrictHttpResponse<GarageRequestDto>> {
  const rb = new RequestBuilder(rootUrl, garageRequestsControllerGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GarageRequestDto>;
    })
  );
}

garageRequestsControllerGet.PATH = '/api/v1/garage/requests/{id}';
