/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeclineRequestDto } from '../../models/decline-request-dto';
import { GarageRecipientDto } from '../../models/garage-recipient-dto';

export interface GarageRequestsControllerDecline$Params {
  id: string;
      body: DeclineRequestDto
}

export function garageRequestsControllerDecline(http: HttpClient, rootUrl: string, params: GarageRequestsControllerDecline$Params, context?: HttpContext): Observable<StrictHttpResponse<GarageRecipientDto>> {
  const rb = new RequestBuilder(rootUrl, garageRequestsControllerDecline.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GarageRecipientDto>;
    })
  );
}

garageRequestsControllerDecline.PATH = '/api/v1/garage/requests/{id}/decline';
