/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InviteTokenDto } from '../../models/invite-token-dto';
import { InviteViewDto } from '../../models/invite-view-dto';

export interface InvitesControllerCheck$Params {
      body: InviteTokenDto
}

export function invitesControllerCheck(http: HttpClient, rootUrl: string, params: InvitesControllerCheck$Params, context?: HttpContext): Observable<StrictHttpResponse<InviteViewDto>> {
  const rb = new RequestBuilder(rootUrl, invitesControllerCheck.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InviteViewDto>;
    })
  );
}

invitesControllerCheck.PATH = '/api/v1/invites/check';
