/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuditHistoryPageDto } from '../../models/audit-history-page-dto';

export interface AuditHistoryControllerList$Params {

/**
 * Staff: their own garage only; admin: any garage
 */
  garageId?: string;

/**
 * Who made the change
 */
  actorId?: string;
  jobId?: string;
  area?: 'requests' | 'quotes' | 'bookings' | 'jobs' | 'prices' | 'repair_history' | 'photos' | 'garage_profile' | 'team' | 'settings' | 'admin_actions';

/**
 * Inclusive; 7 days before now when absent
 */
  from?: string;

/**
 * Inclusive
 */
  to?: string;

/**
 * The nextCursor of the previous page
 */
  cursor?: string;
}

export function auditHistoryControllerList(http: HttpClient, rootUrl: string, params?: AuditHistoryControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<AuditHistoryPageDto>> {
  const rb = new RequestBuilder(rootUrl, auditHistoryControllerList.PATH, 'get');
  if (params) {
    rb.query('garageId', params.garageId, {});
    rb.query('actorId', params.actorId, {});
    rb.query('jobId', params.jobId, {});
    rb.query('area', params.area, {});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
    rb.query('cursor', params.cursor, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuditHistoryPageDto>;
    })
  );
}

auditHistoryControllerList.PATH = '/api/v1/audit-history';
