/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminAccountsSummaryDto } from '../../models/admin-accounts-summary-dto';

export interface AdminAccountsControllerSummary$Params {
}

export function adminAccountsControllerSummary(http: HttpClient, rootUrl: string, params?: AdminAccountsControllerSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminAccountsSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, adminAccountsControllerSummary.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminAccountsSummaryDto>;
    })
  );
}

adminAccountsControllerSummary.PATH = '/api/v1/admin/accounts/summary';
