/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminGrowthDto } from '../../models/admin-growth-dto';

export interface AdminOverviewControllerGrowth$Params {

/**
 * A key from the overview's cities, or all
 */
  city?: string;
}

export function adminOverviewControllerGrowth(http: HttpClient, rootUrl: string, params?: AdminOverviewControllerGrowth$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminGrowthDto>> {
  const rb = new RequestBuilder(rootUrl, adminOverviewControllerGrowth.PATH, 'get');
  if (params) {
    rb.query('city', params.city, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminGrowthDto>;
    })
  );
}

adminOverviewControllerGrowth.PATH = '/api/v1/admin/growth';
