/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminOverviewDto } from '../../models/admin-overview-dto';

export interface AdminOverviewControllerOverview$Params {

/**
 * A key from the overview's cities, or all
 */
  city?: string;
  period?: 'default' | 'today' | '7d' | '30d' | 'month' | '12m';
}

export function adminOverviewControllerOverview(http: HttpClient, rootUrl: string, params?: AdminOverviewControllerOverview$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminOverviewDto>> {
  const rb = new RequestBuilder(rootUrl, adminOverviewControllerOverview.PATH, 'get');
  if (params) {
    rb.query('city', params.city, {});
    rb.query('period', params.period, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminOverviewDto>;
    })
  );
}

adminOverviewControllerOverview.PATH = '/api/v1/admin/overview';
