/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminAccountsPageDto } from '../../models/admin-accounts-page-dto';

export interface AdminAccountsControllerList$Params {

/**
 * The nextCursor of the previous page
 */
  cursor?: string;
}

export function adminAccountsControllerList(http: HttpClient, rootUrl: string, params?: AdminAccountsControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminAccountsPageDto>> {
  const rb = new RequestBuilder(rootUrl, adminAccountsControllerList.PATH, 'get');
  if (params) {
    rb.query('cursor', params.cursor, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminAccountsPageDto>;
    })
  );
}

adminAccountsControllerList.PATH = '/api/v1/admin/accounts';
