/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChangePlatformRuleDto } from '../../models/change-platform-rule-dto';
import { PlatformRuleDto } from '../../models/platform-rule-dto';

export interface PlatformRulesControllerChange$Params {
  key: string;
      body: ChangePlatformRuleDto
}

export function platformRulesControllerChange(http: HttpClient, rootUrl: string, params: PlatformRulesControllerChange$Params, context?: HttpContext): Observable<StrictHttpResponse<PlatformRuleDto>> {
  const rb = new RequestBuilder(rootUrl, platformRulesControllerChange.PATH, 'patch');
  if (params) {
    rb.path('key', params.key, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlatformRuleDto>;
    })
  );
}

platformRulesControllerChange.PATH = '/api/v1/admin/platform-rules/{key}';
