/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlatformRuleChangeDto } from '../../models/platform-rule-change-dto';

export interface PlatformRuleChangesControllerApprove$Params {
  id: string;
}

export function platformRuleChangesControllerApprove(http: HttpClient, rootUrl: string, params: PlatformRuleChangesControllerApprove$Params, context?: HttpContext): Observable<StrictHttpResponse<PlatformRuleChangeDto>> {
  const rb = new RequestBuilder(rootUrl, platformRuleChangesControllerApprove.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlatformRuleChangeDto>;
    })
  );
}

platformRuleChangesControllerApprove.PATH = '/api/v1/admin/platform-rule-changes/{id}/approve';
