/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlatformRuleChangeDto } from '../../models/platform-rule-change-dto';
import { RequestPlatformRuleChangeDto } from '../../models/request-platform-rule-change-dto';

export interface PlatformRuleChangesControllerRequest$Params {
      body: RequestPlatformRuleChangeDto
}

export function platformRuleChangesControllerRequest(http: HttpClient, rootUrl: string, params: PlatformRuleChangesControllerRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<PlatformRuleChangeDto>> {
  const rb = new RequestBuilder(rootUrl, platformRuleChangesControllerRequest.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlatformRuleChangeDto>;
    })
  );
}

platformRuleChangesControllerRequest.PATH = '/api/v1/admin/platform-rule-changes';
