/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlatformRuleChangesDto } from '../../models/platform-rule-changes-dto';

export interface PlatformRuleChangesControllerList$Params {
  key: string;
}

export function platformRuleChangesControllerList(http: HttpClient, rootUrl: string, params: PlatformRuleChangesControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<PlatformRuleChangesDto>> {
  const rb = new RequestBuilder(rootUrl, platformRuleChangesControllerList.PATH, 'get');
  if (params) {
    rb.query('key', params.key, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlatformRuleChangesDto>;
    })
  );
}

platformRuleChangesControllerList.PATH = '/api/v1/admin/platform-rule-changes';
