/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RecordVerificationCheckDto } from '../../models/record-verification-check-dto';
import { VerificationCheckRecordedDto } from '../../models/verification-check-recorded-dto';

export interface VerificationChecksControllerRecord$Params {
  id: string;
  kind: string;
      body: RecordVerificationCheckDto
}

export function verificationChecksControllerRecord(http: HttpClient, rootUrl: string, params: VerificationChecksControllerRecord$Params, context?: HttpContext): Observable<StrictHttpResponse<VerificationCheckRecordedDto>> {
  const rb = new RequestBuilder(rootUrl, verificationChecksControllerRecord.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('kind', params.kind, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VerificationCheckRecordedDto>;
    })
  );
}

verificationChecksControllerRecord.PATH = '/api/v1/admin/verification-files/{id}/checks/{kind}';
