/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HealthReadyDto } from '../../models/health-ready-dto';

export interface HealthControllerReady$Params {
}

export function healthControllerReady(http: HttpClient, rootUrl: string, params?: HealthControllerReady$Params, context?: HttpContext): Observable<StrictHttpResponse<HealthReadyDto>> {
  const rb = new RequestBuilder(rootUrl, healthControllerReady.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HealthReadyDto>;
    })
  );
}

healthControllerReady.PATH = '/health/ready';
