/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HomeDto } from '../../models/home-dto';

export interface HomeControllerForBrand$Params {

/**
 * The brand, by its catalogue slug
 */
  brand: string;

/**
 * The place as "lat,lng"; accepted and ignored until a place narrows the count
 */
  near?: string;
}

export function homeControllerForBrand(http: HttpClient, rootUrl: string, params: HomeControllerForBrand$Params, context?: HttpContext): Observable<StrictHttpResponse<HomeDto>> {
  const rb = new RequestBuilder(rootUrl, homeControllerForBrand.PATH, 'get');
  if (params) {
    rb.query('brand', params.brand, {});
    rb.query('near', params.near, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HomeDto>;
    })
  );
}

homeControllerForBrand.PATH = '/api/v1/home';
