/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { adminAccountsControllerList } from '../fn/admin/admin-accounts-controller-list';
import { AdminAccountsControllerList$Params } from '../fn/admin/admin-accounts-controller-list';
import { adminAccountsControllerSummary } from '../fn/admin/admin-accounts-controller-summary';
import { AdminAccountsControllerSummary$Params } from '../fn/admin/admin-accounts-controller-summary';
import { AdminAccountsPageDto } from '../models/admin-accounts-page-dto';
import { AdminAccountsSummaryDto } from '../models/admin-accounts-summary-dto';
import { AdminGrowthDto } from '../models/admin-growth-dto';
import { adminOverviewControllerGrowth } from '../fn/admin/admin-overview-controller-growth';
import { AdminOverviewControllerGrowth$Params } from '../fn/admin/admin-overview-controller-growth';
import { adminOverviewControllerOverview } from '../fn/admin/admin-overview-controller-overview';
import { AdminOverviewControllerOverview$Params } from '../fn/admin/admin-overview-controller-overview';
import { AdminOverviewDto } from '../models/admin-overview-dto';
import { PlatformRuleDto } from '../models/platform-rule-dto';
import { platformRulesControllerChange } from '../fn/admin/platform-rules-controller-change';
import { PlatformRulesControllerChange$Params } from '../fn/admin/platform-rules-controller-change';
import { platformRulesControllerList } from '../fn/admin/platform-rules-controller-list';
import { PlatformRulesControllerList$Params } from '../fn/admin/platform-rules-controller-list';
import { PlatformRulesDto } from '../models/platform-rules-dto';
import { VerificationCheckRecordedDto } from '../models/verification-check-recorded-dto';
import { verificationChecksControllerRecord } from '../fn/admin/verification-checks-controller-record';
import { VerificationChecksControllerRecord$Params } from '../fn/admin/verification-checks-controller-record';

@Injectable({ providedIn: 'root' })
export class AdminService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `adminAccountsControllerList()` */
  static readonly AdminAccountsControllerListPath = '/api/v1/admin/accounts';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminAccountsControllerList()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminAccountsControllerList$Response(params?: AdminAccountsControllerList$Params, context?: HttpContext): Promise<StrictHttpResponse<AdminAccountsPageDto>> {
    const obs = adminAccountsControllerList(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminAccountsControllerList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminAccountsControllerList(params?: AdminAccountsControllerList$Params, context?: HttpContext): Promise<AdminAccountsPageDto> {
    const resp = this.adminAccountsControllerList$Response(params, context);
    return resp.then((r: StrictHttpResponse<AdminAccountsPageDto>): AdminAccountsPageDto => r.body);
  }

  /** Path part for operation `adminAccountsControllerSummary()` */
  static readonly AdminAccountsControllerSummaryPath = '/api/v1/admin/accounts/summary';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminAccountsControllerSummary()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminAccountsControllerSummary$Response(params?: AdminAccountsControllerSummary$Params, context?: HttpContext): Promise<StrictHttpResponse<AdminAccountsSummaryDto>> {
    const obs = adminAccountsControllerSummary(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminAccountsControllerSummary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminAccountsControllerSummary(params?: AdminAccountsControllerSummary$Params, context?: HttpContext): Promise<AdminAccountsSummaryDto> {
    const resp = this.adminAccountsControllerSummary$Response(params, context);
    return resp.then((r: StrictHttpResponse<AdminAccountsSummaryDto>): AdminAccountsSummaryDto => r.body);
  }

  /** Path part for operation `adminOverviewControllerOverview()` */
  static readonly AdminOverviewControllerOverviewPath = '/api/v1/admin/overview';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminOverviewControllerOverview()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminOverviewControllerOverview$Response(params?: AdminOverviewControllerOverview$Params, context?: HttpContext): Promise<StrictHttpResponse<AdminOverviewDto>> {
    const obs = adminOverviewControllerOverview(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminOverviewControllerOverview$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminOverviewControllerOverview(params?: AdminOverviewControllerOverview$Params, context?: HttpContext): Promise<AdminOverviewDto> {
    const resp = this.adminOverviewControllerOverview$Response(params, context);
    return resp.then((r: StrictHttpResponse<AdminOverviewDto>): AdminOverviewDto => r.body);
  }

  /** Path part for operation `adminOverviewControllerGrowth()` */
  static readonly AdminOverviewControllerGrowthPath = '/api/v1/admin/growth';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminOverviewControllerGrowth()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminOverviewControllerGrowth$Response(params?: AdminOverviewControllerGrowth$Params, context?: HttpContext): Promise<StrictHttpResponse<AdminGrowthDto>> {
    const obs = adminOverviewControllerGrowth(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminOverviewControllerGrowth$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminOverviewControllerGrowth(params?: AdminOverviewControllerGrowth$Params, context?: HttpContext): Promise<AdminGrowthDto> {
    const resp = this.adminOverviewControllerGrowth$Response(params, context);
    return resp.then((r: StrictHttpResponse<AdminGrowthDto>): AdminGrowthDto => r.body);
  }

  /** Path part for operation `verificationChecksControllerRecord()` */
  static readonly VerificationChecksControllerRecordPath = '/api/v1/admin/verification-files/{id}/checks/{kind}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `verificationChecksControllerRecord()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  verificationChecksControllerRecord$Response(params: VerificationChecksControllerRecord$Params, context?: HttpContext): Promise<StrictHttpResponse<VerificationCheckRecordedDto>> {
    const obs = verificationChecksControllerRecord(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `verificationChecksControllerRecord$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  verificationChecksControllerRecord(params: VerificationChecksControllerRecord$Params, context?: HttpContext): Promise<VerificationCheckRecordedDto> {
    const resp = this.verificationChecksControllerRecord$Response(params, context);
    return resp.then((r: StrictHttpResponse<VerificationCheckRecordedDto>): VerificationCheckRecordedDto => r.body);
  }

  /** Path part for operation `platformRulesControllerList()` */
  static readonly PlatformRulesControllerListPath = '/api/v1/admin/platform-rules';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `platformRulesControllerList()` instead.
   *
   * This method doesn't expect any request body.
   */
  platformRulesControllerList$Response(params?: PlatformRulesControllerList$Params, context?: HttpContext): Promise<StrictHttpResponse<PlatformRulesDto>> {
    const obs = platformRulesControllerList(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `platformRulesControllerList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  platformRulesControllerList(params?: PlatformRulesControllerList$Params, context?: HttpContext): Promise<PlatformRulesDto> {
    const resp = this.platformRulesControllerList$Response(params, context);
    return resp.then((r: StrictHttpResponse<PlatformRulesDto>): PlatformRulesDto => r.body);
  }

  /** Path part for operation `platformRulesControllerChange()` */
  static readonly PlatformRulesControllerChangePath = '/api/v1/admin/platform-rules/{key}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `platformRulesControllerChange()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  platformRulesControllerChange$Response(params: PlatformRulesControllerChange$Params, context?: HttpContext): Promise<StrictHttpResponse<PlatformRuleDto>> {
    const obs = platformRulesControllerChange(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `platformRulesControllerChange$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  platformRulesControllerChange(params: PlatformRulesControllerChange$Params, context?: HttpContext): Promise<PlatformRuleDto> {
    const resp = this.platformRulesControllerChange$Response(params, context);
    return resp.then((r: StrictHttpResponse<PlatformRuleDto>): PlatformRuleDto => r.body);
  }

}
