/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { adminOverviewControllerOverview } from '../fn/admin/admin-overview-controller-overview';
import { AdminOverviewControllerOverview$Params } from '../fn/admin/admin-overview-controller-overview';
import { AdminOverviewDto } from '../models/admin-overview-dto';
import { VerificationCheckRecordedDto } from '../models/verification-check-recorded-dto';
import { verificationChecksControllerRecord } from '../fn/admin/verification-checks-controller-record';
import { VerificationChecksControllerRecord$Params } from '../fn/admin/verification-checks-controller-record';

@Injectable({ providedIn: 'root' })
export class AdminService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `adminOverviewControllerOverview()` */
  static readonly AdminOverviewControllerOverviewPath = '/api/v1/admin/overview';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminOverviewControllerOverview()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminOverviewControllerOverview$Response(params?: AdminOverviewControllerOverview$Params, context?: HttpContext): Promise<StrictHttpResponse<AdminOverviewDto>> {
    const obs = adminOverviewControllerOverview(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminOverviewControllerOverview$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminOverviewControllerOverview(params?: AdminOverviewControllerOverview$Params, context?: HttpContext): Promise<AdminOverviewDto> {
    const resp = this.adminOverviewControllerOverview$Response(params, context);
    return resp.then((r: StrictHttpResponse<AdminOverviewDto>): AdminOverviewDto => r.body);
  }

  /** Path part for operation `verificationChecksControllerRecord()` */
  static readonly VerificationChecksControllerRecordPath = '/api/v1/admin/verification-files/{id}/checks/{kind}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `verificationChecksControllerRecord()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  verificationChecksControllerRecord$Response(params: VerificationChecksControllerRecord$Params, context?: HttpContext): Promise<StrictHttpResponse<VerificationCheckRecordedDto>> {
    const obs = verificationChecksControllerRecord(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `verificationChecksControllerRecord$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  verificationChecksControllerRecord(params: VerificationChecksControllerRecord$Params, context?: HttpContext): Promise<VerificationCheckRecordedDto> {
    const resp = this.verificationChecksControllerRecord$Response(params, context);
    return resp.then((r: StrictHttpResponse<VerificationCheckRecordedDto>): VerificationCheckRecordedDto => r.body);
  }

}
