/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { auditHistoryControllerList } from '../fn/audit-history/audit-history-controller-list';
import { AuditHistoryControllerList$Params } from '../fn/audit-history/audit-history-controller-list';
import { AuditHistoryPageDto } from '../models/audit-history-page-dto';

@Injectable({ providedIn: 'root' })
export class AuditHistoryService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `auditHistoryControllerList()` */
  static readonly AuditHistoryControllerListPath = '/api/v1/audit-history';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `auditHistoryControllerList()` instead.
   *
   * This method doesn't expect any request body.
   */
  auditHistoryControllerList$Response(params?: AuditHistoryControllerList$Params, context?: HttpContext): Promise<StrictHttpResponse<AuditHistoryPageDto>> {
    const obs = auditHistoryControllerList(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `auditHistoryControllerList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  auditHistoryControllerList(params?: AuditHistoryControllerList$Params, context?: HttpContext): Promise<AuditHistoryPageDto> {
    const resp = this.auditHistoryControllerList$Response(params, context);
    return resp.then((r: StrictHttpResponse<AuditHistoryPageDto>): AuditHistoryPageDto => r.body);
  }

}
