/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { authControllerRefresh } from '../fn/auth/auth-controller-refresh';
import { AuthControllerRefresh$Params } from '../fn/auth/auth-controller-refresh';
import { authControllerSignIn } from '../fn/auth/auth-controller-sign-in';
import { AuthControllerSignIn$Params } from '../fn/auth/auth-controller-sign-in';
import { authControllerSignOut } from '../fn/auth/auth-controller-sign-out';
import { AuthControllerSignOut$Params } from '../fn/auth/auth-controller-sign-out';
import { authControllerSignOutEverywhere } from '../fn/auth/auth-controller-sign-out-everywhere';
import { AuthControllerSignOutEverywhere$Params } from '../fn/auth/auth-controller-sign-out-everywhere';
import { authControllerSignUp } from '../fn/auth/auth-controller-sign-up';
import { AuthControllerSignUp$Params } from '../fn/auth/auth-controller-sign-up';
import { ConfirmEmailAnswerDto } from '../models/confirm-email-answer-dto';
import { emailConfirmationControllerConfirm } from '../fn/auth/email-confirmation-controller-confirm';
import { EmailConfirmationControllerConfirm$Params } from '../fn/auth/email-confirmation-controller-confirm';
import { emailConfirmationControllerResend } from '../fn/auth/email-confirmation-controller-resend';
import { EmailConfirmationControllerResend$Params } from '../fn/auth/email-confirmation-controller-resend';
import { SessionDto } from '../models/session-dto';

@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `authControllerSignIn()` */
  static readonly AuthControllerSignInPath = '/api/v1/auth/sign-in';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerSignIn()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerSignIn$Response(params: AuthControllerSignIn$Params, context?: HttpContext): Promise<StrictHttpResponse<SessionDto>> {
    const obs = authControllerSignIn(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerSignIn$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerSignIn(params: AuthControllerSignIn$Params, context?: HttpContext): Promise<SessionDto> {
    const resp = this.authControllerSignIn$Response(params, context);
    return resp.then((r: StrictHttpResponse<SessionDto>): SessionDto => r.body);
  }

  /** Path part for operation `authControllerSignUp()` */
  static readonly AuthControllerSignUpPath = '/api/v1/auth/sign-up';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerSignUp()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerSignUp$Response(params: AuthControllerSignUp$Params, context?: HttpContext): Promise<StrictHttpResponse<SessionDto>> {
    const obs = authControllerSignUp(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerSignUp$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerSignUp(params: AuthControllerSignUp$Params, context?: HttpContext): Promise<SessionDto> {
    const resp = this.authControllerSignUp$Response(params, context);
    return resp.then((r: StrictHttpResponse<SessionDto>): SessionDto => r.body);
  }

  /** Path part for operation `authControllerRefresh()` */
  static readonly AuthControllerRefreshPath = '/api/v1/auth/refresh';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerRefresh()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerRefresh$Response(params?: AuthControllerRefresh$Params, context?: HttpContext): Promise<StrictHttpResponse<SessionDto>> {
    const obs = authControllerRefresh(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerRefresh$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerRefresh(params?: AuthControllerRefresh$Params, context?: HttpContext): Promise<SessionDto> {
    const resp = this.authControllerRefresh$Response(params, context);
    return resp.then((r: StrictHttpResponse<SessionDto>): SessionDto => r.body);
  }

  /** Path part for operation `authControllerSignOutEverywhere()` */
  static readonly AuthControllerSignOutEverywherePath = '/api/v1/auth/sign-out-everywhere';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerSignOutEverywhere()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerSignOutEverywhere$Response(params?: AuthControllerSignOutEverywhere$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = authControllerSignOutEverywhere(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerSignOutEverywhere$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerSignOutEverywhere(params?: AuthControllerSignOutEverywhere$Params, context?: HttpContext): Promise<void> {
    const resp = this.authControllerSignOutEverywhere$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `authControllerSignOut()` */
  static readonly AuthControllerSignOutPath = '/api/v1/auth/sign-out';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerSignOut()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerSignOut$Response(params?: AuthControllerSignOut$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = authControllerSignOut(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerSignOut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerSignOut(params?: AuthControllerSignOut$Params, context?: HttpContext): Promise<void> {
    const resp = this.authControllerSignOut$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `emailConfirmationControllerConfirm()` */
  static readonly EmailConfirmationControllerConfirmPath = '/api/v1/auth/confirm-email';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `emailConfirmationControllerConfirm()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  emailConfirmationControllerConfirm$Response(params: EmailConfirmationControllerConfirm$Params, context?: HttpContext): Promise<StrictHttpResponse<ConfirmEmailAnswerDto>> {
    const obs = emailConfirmationControllerConfirm(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `emailConfirmationControllerConfirm$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  emailConfirmationControllerConfirm(params: EmailConfirmationControllerConfirm$Params, context?: HttpContext): Promise<ConfirmEmailAnswerDto> {
    const resp = this.emailConfirmationControllerConfirm$Response(params, context);
    return resp.then((r: StrictHttpResponse<ConfirmEmailAnswerDto>): ConfirmEmailAnswerDto => r.body);
  }

  /** Path part for operation `emailConfirmationControllerResend()` */
  static readonly EmailConfirmationControllerResendPath = '/api/v1/auth/confirm-email/resend';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `emailConfirmationControllerResend()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  emailConfirmationControllerResend$Response(params: EmailConfirmationControllerResend$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = emailConfirmationControllerResend(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `emailConfirmationControllerResend$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  emailConfirmationControllerResend(params: EmailConfirmationControllerResend$Params, context?: HttpContext): Promise<void> {
    const resp = this.emailConfirmationControllerResend$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
