/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BrandDto } from '../models/brand-dto';
import { BrandPageDto } from '../models/brand-page-dto';
import { brandsControllerSearch } from '../fn/brands/brands-controller-search';
import { BrandsControllerSearch$Params } from '../fn/brands/brands-controller-search';
import { popularBrandsControllerTiles } from '../fn/brands/popular-brands-controller-tiles';
import { PopularBrandsControllerTiles$Params } from '../fn/brands/popular-brands-controller-tiles';

@Injectable({ providedIn: 'root' })
export class BrandsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `brandsControllerSearch()` */
  static readonly BrandsControllerSearchPath = '/api/v1/brands';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `brandsControllerSearch()` instead.
   *
   * This method doesn't expect any request body.
   */
  brandsControllerSearch$Response(params?: BrandsControllerSearch$Params, context?: HttpContext): Promise<StrictHttpResponse<BrandPageDto>> {
    const obs = brandsControllerSearch(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `brandsControllerSearch$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  brandsControllerSearch(params?: BrandsControllerSearch$Params, context?: HttpContext): Promise<BrandPageDto> {
    const resp = this.brandsControllerSearch$Response(params, context);
    return resp.then((r: StrictHttpResponse<BrandPageDto>): BrandPageDto => r.body);
  }

  /** Path part for operation `popularBrandsControllerTiles()` */
  static readonly PopularBrandsControllerTilesPath = '/api/v1/brands/popular';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `popularBrandsControllerTiles()` instead.
   *
   * This method doesn't expect any request body.
   */
  popularBrandsControllerTiles$Response(params?: PopularBrandsControllerTiles$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<BrandDto>>> {
    const obs = popularBrandsControllerTiles(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `popularBrandsControllerTiles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  popularBrandsControllerTiles(params?: PopularBrandsControllerTiles$Params, context?: HttpContext): Promise<Array<BrandDto>> {
    const resp = this.popularBrandsControllerTiles$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<BrandDto>>): Array<BrandDto> => r.body);
  }

}
