/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CarDto } from '../models/car-dto';
import { CarListDto } from '../models/car-list-dto';
import { carsControllerCreate } from '../fn/cars/cars-controller-create';
import { CarsControllerCreate$Params } from '../fn/cars/cars-controller-create';
import { carsControllerList } from '../fn/cars/cars-controller-list';
import { CarsControllerList$Params } from '../fn/cars/cars-controller-list';

@Injectable({ providedIn: 'root' })
export class CarsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `carsControllerList()` */
  static readonly CarsControllerListPath = '/api/v1/cars';

  /**
   * The caller's cars, newest first.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `carsControllerList()` instead.
   *
   * This method doesn't expect any request body.
   */
  carsControllerList$Response(params?: CarsControllerList$Params, context?: HttpContext): Promise<StrictHttpResponse<CarListDto>> {
    const obs = carsControllerList(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * The caller's cars, newest first.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `carsControllerList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  carsControllerList(params?: CarsControllerList$Params, context?: HttpContext): Promise<CarListDto> {
    const resp = this.carsControllerList$Response(params, context);
    return resp.then((r: StrictHttpResponse<CarListDto>): CarListDto => r.body);
  }

  /** Path part for operation `carsControllerCreate()` */
  static readonly CarsControllerCreatePath = '/api/v1/cars';

  /**
   * Add a car to the caller's account.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `carsControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  carsControllerCreate$Response(params: CarsControllerCreate$Params, context?: HttpContext): Promise<StrictHttpResponse<CarDto>> {
    const obs = carsControllerCreate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Add a car to the caller's account.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `carsControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  carsControllerCreate(params: CarsControllerCreate$Params, context?: HttpContext): Promise<CarDto> {
    const resp = this.carsControllerCreate$Response(params, context);
    return resp.then((r: StrictHttpResponse<CarDto>): CarDto => r.body);
  }

}
