/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { JobTypeListDto } from '../models/job-type-list-dto';
import { jobTypesControllerSearch } from '../fn/catalogue/job-types-controller-search';
import { JobTypesControllerSearch$Params } from '../fn/catalogue/job-types-controller-search';

@Injectable({ providedIn: 'root' })
export class CatalogueService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `jobTypesControllerSearch()` */
  static readonly JobTypesControllerSearchPath = '/api/v1/job-types';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `jobTypesControllerSearch()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobTypesControllerSearch$Response(params?: JobTypesControllerSearch$Params, context?: HttpContext): Promise<StrictHttpResponse<JobTypeListDto>> {
    const obs = jobTypesControllerSearch(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `jobTypesControllerSearch$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobTypesControllerSearch(params?: JobTypesControllerSearch$Params, context?: HttpContext): Promise<JobTypeListDto> {
    const resp = this.jobTypesControllerSearch$Response(params, context);
    return resp.then((r: StrictHttpResponse<JobTypeListDto>): JobTypeListDto => r.body);
  }

}
