/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ConsentRecordedDto } from '../models/consent-recorded-dto';
import { consentsControllerMine } from '../fn/consents/consents-controller-mine';
import { ConsentsControllerMine$Params } from '../fn/consents/consents-controller-mine';
import { consentsControllerRecord } from '../fn/consents/consents-controller-record';
import { ConsentsControllerRecord$Params } from '../fn/consents/consents-controller-record';
import { consentsControllerRecordMine } from '../fn/consents/consents-controller-record-mine';
import { ConsentsControllerRecordMine$Params } from '../fn/consents/consents-controller-record-mine';
import { MyConsentsDto } from '../models/my-consents-dto';

@Injectable({ providedIn: 'root' })
export class ConsentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `consentsControllerRecord()` */
  static readonly ConsentsControllerRecordPath = '/api/v1/consents';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `consentsControllerRecord()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  consentsControllerRecord$Response(params: ConsentsControllerRecord$Params, context?: HttpContext): Promise<StrictHttpResponse<ConsentRecordedDto>> {
    const obs = consentsControllerRecord(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `consentsControllerRecord$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  consentsControllerRecord(params: ConsentsControllerRecord$Params, context?: HttpContext): Promise<ConsentRecordedDto> {
    const resp = this.consentsControllerRecord$Response(params, context);
    return resp.then((r: StrictHttpResponse<ConsentRecordedDto>): ConsentRecordedDto => r.body);
  }

  /** Path part for operation `consentsControllerMine()` */
  static readonly ConsentsControllerMinePath = '/api/v1/me/consents';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `consentsControllerMine()` instead.
   *
   * This method doesn't expect any request body.
   */
  consentsControllerMine$Response(params?: ConsentsControllerMine$Params, context?: HttpContext): Promise<StrictHttpResponse<MyConsentsDto>> {
    const obs = consentsControllerMine(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `consentsControllerMine$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  consentsControllerMine(params?: ConsentsControllerMine$Params, context?: HttpContext): Promise<MyConsentsDto> {
    const resp = this.consentsControllerMine$Response(params, context);
    return resp.then((r: StrictHttpResponse<MyConsentsDto>): MyConsentsDto => r.body);
  }

  /** Path part for operation `consentsControllerRecordMine()` */
  static readonly ConsentsControllerRecordMinePath = '/api/v1/me/consents';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `consentsControllerRecordMine()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  consentsControllerRecordMine$Response(params: ConsentsControllerRecordMine$Params, context?: HttpContext): Promise<StrictHttpResponse<ConsentRecordedDto>> {
    const obs = consentsControllerRecordMine(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `consentsControllerRecordMine$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  consentsControllerRecordMine(params: ConsentsControllerRecordMine$Params, context?: HttpContext): Promise<ConsentRecordedDto> {
    const resp = this.consentsControllerRecordMine$Response(params, context);
    return resp.then((r: StrictHttpResponse<ConsentRecordedDto>): ConsentRecordedDto => r.body);
  }

}
