/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { garageJobsControllerGet } from '../fn/garage-jobs/garage-jobs-controller-get';
import { GarageJobsControllerGet$Params } from '../fn/garage-jobs/garage-jobs-controller-get';
import { garageJobsControllerList } from '../fn/garage-jobs/garage-jobs-controller-list';
import { GarageJobsControllerList$Params } from '../fn/garage-jobs/garage-jobs-controller-list';
import { JobDto } from '../models/job-dto';
import { JobListDto } from '../models/job-list-dto';

@Injectable({ providedIn: 'root' })
export class GarageJobsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `garageJobsControllerList()` */
  static readonly GarageJobsControllerListPath = '/api/v1/garage/jobs';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `garageJobsControllerList()` instead.
   *
   * This method doesn't expect any request body.
   */
  garageJobsControllerList$Response(params?: GarageJobsControllerList$Params, context?: HttpContext): Promise<StrictHttpResponse<JobListDto>> {
    const obs = garageJobsControllerList(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `garageJobsControllerList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  garageJobsControllerList(params?: GarageJobsControllerList$Params, context?: HttpContext): Promise<JobListDto> {
    const resp = this.garageJobsControllerList$Response(params, context);
    return resp.then((r: StrictHttpResponse<JobListDto>): JobListDto => r.body);
  }

  /** Path part for operation `garageJobsControllerGet()` */
  static readonly GarageJobsControllerGetPath = '/api/v1/garage/jobs/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `garageJobsControllerGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  garageJobsControllerGet$Response(params: GarageJobsControllerGet$Params, context?: HttpContext): Promise<StrictHttpResponse<JobDto>> {
    const obs = garageJobsControllerGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `garageJobsControllerGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  garageJobsControllerGet(params: GarageJobsControllerGet$Params, context?: HttpContext): Promise<JobDto> {
    const resp = this.garageJobsControllerGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<JobDto>): JobDto => r.body);
  }

}
