/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { GarageBrandAnswerDto } from '../models/garage-brand-answer-dto';
import { garageBrandsControllerReplace } from '../fn/garages/garage-brands-controller-replace';
import { GarageBrandsControllerReplace$Params } from '../fn/garages/garage-brands-controller-replace';
import { garageInvitesControllerResend } from '../fn/garages/garage-invites-controller-resend';
import { GarageInvitesControllerResend$Params } from '../fn/garages/garage-invites-controller-resend';
import { garageInvitesControllerRevoke } from '../fn/garages/garage-invites-controller-revoke';
import { GarageInvitesControllerRevoke$Params } from '../fn/garages/garage-invites-controller-revoke';
import { garageInvitesControllerSend } from '../fn/garages/garage-invites-controller-send';
import { GarageInvitesControllerSend$Params } from '../fn/garages/garage-invites-controller-send';
import { GarageReportCreatedDto } from '../models/garage-report-created-dto';
import { garageReportsControllerReport } from '../fn/garages/garage-reports-controller-report';
import { GarageReportsControllerReport$Params } from '../fn/garages/garage-reports-controller-report';
import { garageSettingsControllerUpdate } from '../fn/garages/garage-settings-controller-update';
import { GarageSettingsControllerUpdate$Params } from '../fn/garages/garage-settings-controller-update';
import { GarageSettingsDto } from '../models/garage-settings-dto';
import { PublicGarageDto } from '../models/public-garage-dto';
import { publicGaragesControllerBySlug } from '../fn/garages/public-garages-controller-by-slug';
import { PublicGaragesControllerBySlug$Params } from '../fn/garages/public-garages-controller-by-slug';
import { StaffInviteSentDto } from '../models/staff-invite-sent-dto';

@Injectable({ providedIn: 'root' })
export class GaragesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `garageBrandsControllerReplace()` */
  static readonly GarageBrandsControllerReplacePath = '/api/v1/garages/{garageId}/brands';

  /**
   * Replace the garage's brand answer: taken, refused, the texts.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `garageBrandsControllerReplace()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  garageBrandsControllerReplace$Response(params: GarageBrandsControllerReplace$Params, context?: HttpContext): Promise<StrictHttpResponse<GarageBrandAnswerDto>> {
    const obs = garageBrandsControllerReplace(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Replace the garage's brand answer: taken, refused, the texts.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `garageBrandsControllerReplace$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  garageBrandsControllerReplace(params: GarageBrandsControllerReplace$Params, context?: HttpContext): Promise<GarageBrandAnswerDto> {
    const resp = this.garageBrandsControllerReplace$Response(params, context);
    return resp.then((r: StrictHttpResponse<GarageBrandAnswerDto>): GarageBrandAnswerDto => r.body);
  }

  /** Path part for operation `garageInvitesControllerSend()` */
  static readonly GarageInvitesControllerSendPath = '/api/v1/garages/{garageId}/invites';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `garageInvitesControllerSend()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  garageInvitesControllerSend$Response(params: GarageInvitesControllerSend$Params, context?: HttpContext): Promise<StrictHttpResponse<StaffInviteSentDto>> {
    const obs = garageInvitesControllerSend(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `garageInvitesControllerSend$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  garageInvitesControllerSend(params: GarageInvitesControllerSend$Params, context?: HttpContext): Promise<StaffInviteSentDto> {
    const resp = this.garageInvitesControllerSend$Response(params, context);
    return resp.then((r: StrictHttpResponse<StaffInviteSentDto>): StaffInviteSentDto => r.body);
  }

  /** Path part for operation `garageInvitesControllerResend()` */
  static readonly GarageInvitesControllerResendPath = '/api/v1/garages/{garageId}/invites/{id}/resend';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `garageInvitesControllerResend()` instead.
   *
   * This method doesn't expect any request body.
   */
  garageInvitesControllerResend$Response(params: GarageInvitesControllerResend$Params, context?: HttpContext): Promise<StrictHttpResponse<StaffInviteSentDto>> {
    const obs = garageInvitesControllerResend(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `garageInvitesControllerResend$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  garageInvitesControllerResend(params: GarageInvitesControllerResend$Params, context?: HttpContext): Promise<StaffInviteSentDto> {
    const resp = this.garageInvitesControllerResend$Response(params, context);
    return resp.then((r: StrictHttpResponse<StaffInviteSentDto>): StaffInviteSentDto => r.body);
  }

  /** Path part for operation `garageInvitesControllerRevoke()` */
  static readonly GarageInvitesControllerRevokePath = '/api/v1/garages/{garageId}/invites/{id}/revoke';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `garageInvitesControllerRevoke()` instead.
   *
   * This method doesn't expect any request body.
   */
  garageInvitesControllerRevoke$Response(params: GarageInvitesControllerRevoke$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = garageInvitesControllerRevoke(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `garageInvitesControllerRevoke$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  garageInvitesControllerRevoke(params: GarageInvitesControllerRevoke$Params, context?: HttpContext): Promise<void> {
    const resp = this.garageInvitesControllerRevoke$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `garageReportsControllerReport()` */
  static readonly GarageReportsControllerReportPath = '/api/v1/garages/{id}/reports';

  /**
   * Report a listed garage; its verification goes back to review.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `garageReportsControllerReport()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  garageReportsControllerReport$Response(params: GarageReportsControllerReport$Params, context?: HttpContext): Promise<StrictHttpResponse<GarageReportCreatedDto>> {
    const obs = garageReportsControllerReport(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Report a listed garage; its verification goes back to review.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `garageReportsControllerReport$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  garageReportsControllerReport(params: GarageReportsControllerReport$Params, context?: HttpContext): Promise<GarageReportCreatedDto> {
    const resp = this.garageReportsControllerReport$Response(params, context);
    return resp.then((r: StrictHttpResponse<GarageReportCreatedDto>): GarageReportCreatedDto => r.body);
  }

  /** Path part for operation `garageSettingsControllerUpdate()` */
  static readonly GarageSettingsControllerUpdatePath = '/api/v1/garages/{garageId}';

  /**
   * Change the garage's payment methods or courtesy car price.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `garageSettingsControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  garageSettingsControllerUpdate$Response(params: GarageSettingsControllerUpdate$Params, context?: HttpContext): Promise<StrictHttpResponse<GarageSettingsDto>> {
    const obs = garageSettingsControllerUpdate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Change the garage's payment methods or courtesy car price.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `garageSettingsControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  garageSettingsControllerUpdate(params: GarageSettingsControllerUpdate$Params, context?: HttpContext): Promise<GarageSettingsDto> {
    const resp = this.garageSettingsControllerUpdate$Response(params, context);
    return resp.then((r: StrictHttpResponse<GarageSettingsDto>): GarageSettingsDto => r.body);
  }

  /** Path part for operation `publicGaragesControllerBySlug()` */
  static readonly PublicGaragesControllerBySlugPath = '/api/v1/garages/{slug}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicGaragesControllerBySlug()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicGaragesControllerBySlug$Response(params: PublicGaragesControllerBySlug$Params, context?: HttpContext): Promise<StrictHttpResponse<PublicGarageDto>> {
    const obs = publicGaragesControllerBySlug(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicGaragesControllerBySlug$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicGaragesControllerBySlug(params: PublicGaragesControllerBySlug$Params, context?: HttpContext): Promise<PublicGarageDto> {
    const resp = this.publicGaragesControllerBySlug$Response(params, context);
    return resp.then((r: StrictHttpResponse<PublicGarageDto>): PublicGarageDto => r.body);
  }

}
