/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { GarageRecipientDto } from '../models/garage-recipient-dto';
import { GarageRequestDto } from '../models/garage-request-dto';
import { GarageRequestListDto } from '../models/garage-request-list-dto';
import { garageRequestsControllerDecline } from '../fn/garage-requests/garage-requests-controller-decline';
import { GarageRequestsControllerDecline$Params } from '../fn/garage-requests/garage-requests-controller-decline';
import { garageRequestsControllerGet } from '../fn/garage-requests/garage-requests-controller-get';
import { GarageRequestsControllerGet$Params } from '../fn/garage-requests/garage-requests-controller-get';
import { garageRequestsControllerList } from '../fn/garage-requests/garage-requests-controller-list';
import { GarageRequestsControllerList$Params } from '../fn/garage-requests/garage-requests-controller-list';

@Injectable({ providedIn: 'root' })
export class GarageRequestsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `garageRequestsControllerList()` */
  static readonly GarageRequestsControllerListPath = '/api/v1/garage/requests';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `garageRequestsControllerList()` instead.
   *
   * This method doesn't expect any request body.
   */
  garageRequestsControllerList$Response(params?: GarageRequestsControllerList$Params, context?: HttpContext): Promise<StrictHttpResponse<GarageRequestListDto>> {
    const obs = garageRequestsControllerList(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `garageRequestsControllerList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  garageRequestsControllerList(params?: GarageRequestsControllerList$Params, context?: HttpContext): Promise<GarageRequestListDto> {
    const resp = this.garageRequestsControllerList$Response(params, context);
    return resp.then((r: StrictHttpResponse<GarageRequestListDto>): GarageRequestListDto => r.body);
  }

  /** Path part for operation `garageRequestsControllerGet()` */
  static readonly GarageRequestsControllerGetPath = '/api/v1/garage/requests/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `garageRequestsControllerGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  garageRequestsControllerGet$Response(params: GarageRequestsControllerGet$Params, context?: HttpContext): Promise<StrictHttpResponse<GarageRequestDto>> {
    const obs = garageRequestsControllerGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `garageRequestsControllerGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  garageRequestsControllerGet(params: GarageRequestsControllerGet$Params, context?: HttpContext): Promise<GarageRequestDto> {
    const resp = this.garageRequestsControllerGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<GarageRequestDto>): GarageRequestDto => r.body);
  }

  /** Path part for operation `garageRequestsControllerDecline()` */
  static readonly GarageRequestsControllerDeclinePath = '/api/v1/garage/requests/{id}/decline';

  /**
   * Decline a request with one of the four reasons.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `garageRequestsControllerDecline()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  garageRequestsControllerDecline$Response(params: GarageRequestsControllerDecline$Params, context?: HttpContext): Promise<StrictHttpResponse<GarageRecipientDto>> {
    const obs = garageRequestsControllerDecline(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Decline a request with one of the four reasons.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `garageRequestsControllerDecline$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  garageRequestsControllerDecline(params: GarageRequestsControllerDecline$Params, context?: HttpContext): Promise<GarageRecipientDto> {
    const resp = this.garageRequestsControllerDecline$Response(params, context);
    return resp.then((r: StrictHttpResponse<GarageRecipientDto>): GarageRecipientDto => r.body);
  }

}
