/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { healthControllerLive } from '../fn/health/health-controller-live';
import { HealthControllerLive$Params } from '../fn/health/health-controller-live';
import { healthControllerReady } from '../fn/health/health-controller-ready';
import { HealthControllerReady$Params } from '../fn/health/health-controller-ready';
import { HealthLiveDto } from '../models/health-live-dto';
import { HealthReadyDto } from '../models/health-ready-dto';

@Injectable({ providedIn: 'root' })
export class HealthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `healthControllerLive()` */
  static readonly HealthControllerLivePath = '/health/live';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `healthControllerLive()` instead.
   *
   * This method doesn't expect any request body.
   */
  healthControllerLive$Response(params?: HealthControllerLive$Params, context?: HttpContext): Promise<StrictHttpResponse<HealthLiveDto>> {
    const obs = healthControllerLive(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `healthControllerLive$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  healthControllerLive(params?: HealthControllerLive$Params, context?: HttpContext): Promise<HealthLiveDto> {
    const resp = this.healthControllerLive$Response(params, context);
    return resp.then((r: StrictHttpResponse<HealthLiveDto>): HealthLiveDto => r.body);
  }

  /** Path part for operation `healthControllerReady()` */
  static readonly HealthControllerReadyPath = '/health/ready';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `healthControllerReady()` instead.
   *
   * This method doesn't expect any request body.
   */
  healthControllerReady$Response(params?: HealthControllerReady$Params, context?: HttpContext): Promise<StrictHttpResponse<HealthReadyDto>> {
    const obs = healthControllerReady(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `healthControllerReady$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  healthControllerReady(params?: HealthControllerReady$Params, context?: HttpContext): Promise<HealthReadyDto> {
    const resp = this.healthControllerReady$Response(params, context);
    return resp.then((r: StrictHttpResponse<HealthReadyDto>): HealthReadyDto => r.body);
  }

}
