/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { homeControllerForBrand } from '../fn/home/home-controller-for-brand';
import { HomeControllerForBrand$Params } from '../fn/home/home-controller-for-brand';
import { HomeDto } from '../models/home-dto';

@Injectable({ providedIn: 'root' })
export class HomeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `homeControllerForBrand()` */
  static readonly HomeControllerForBrandPath = '/api/v1/home';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `homeControllerForBrand()` instead.
   *
   * This method doesn't expect any request body.
   */
  homeControllerForBrand$Response(params: HomeControllerForBrand$Params, context?: HttpContext): Promise<StrictHttpResponse<HomeDto>> {
    const obs = homeControllerForBrand(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `homeControllerForBrand$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  homeControllerForBrand(params: HomeControllerForBrand$Params, context?: HttpContext): Promise<HomeDto> {
    const resp = this.homeControllerForBrand$Response(params, context);
    return resp.then((r: StrictHttpResponse<HomeDto>): HomeDto => r.body);
  }

}
