/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { invitesControllerAccept } from '../fn/invites/invites-controller-accept';
import { InvitesControllerAccept$Params } from '../fn/invites/invites-controller-accept';
import { invitesControllerCheck } from '../fn/invites/invites-controller-check';
import { InvitesControllerCheck$Params } from '../fn/invites/invites-controller-check';
import { InviteViewDto } from '../models/invite-view-dto';

@Injectable({ providedIn: 'root' })
export class InvitesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `invitesControllerCheck()` */
  static readonly InvitesControllerCheckPath = '/api/v1/invites/check';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `invitesControllerCheck()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  invitesControllerCheck$Response(params: InvitesControllerCheck$Params, context?: HttpContext): Promise<StrictHttpResponse<InviteViewDto>> {
    const obs = invitesControllerCheck(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `invitesControllerCheck$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  invitesControllerCheck(params: InvitesControllerCheck$Params, context?: HttpContext): Promise<InviteViewDto> {
    const resp = this.invitesControllerCheck$Response(params, context);
    return resp.then((r: StrictHttpResponse<InviteViewDto>): InviteViewDto => r.body);
  }

  /** Path part for operation `invitesControllerAccept()` */
  static readonly InvitesControllerAcceptPath = '/api/v1/invites/accept';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `invitesControllerAccept()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  invitesControllerAccept$Response(params: InvitesControllerAccept$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = invitesControllerAccept(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `invitesControllerAccept$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  invitesControllerAccept(params: InvitesControllerAccept$Params, context?: HttpContext): Promise<void> {
    const resp = this.invitesControllerAccept$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
