/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ContinueLinkSentDto } from '../models/continue-link-sent-dto';
import { ListingDraftCreatedDto } from '../models/listing-draft-created-dto';
import { ListingDraftDto } from '../models/listing-draft-dto';
import { ListingDraftSavedDto } from '../models/listing-draft-saved-dto';
import { listingDraftsControllerCreate } from '../fn/listing-drafts/listing-drafts-controller-create';
import { ListingDraftsControllerCreate$Params } from '../fn/listing-drafts/listing-drafts-controller-create';
import { listingDraftsControllerCurrent } from '../fn/listing-drafts/listing-drafts-controller-current';
import { ListingDraftsControllerCurrent$Params } from '../fn/listing-drafts/listing-drafts-controller-current';
import { listingDraftsControllerSave } from '../fn/listing-drafts/listing-drafts-controller-save';
import { ListingDraftsControllerSave$Params } from '../fn/listing-drafts/listing-drafts-controller-save';
import { listingDraftsControllerSendLink } from '../fn/listing-drafts/listing-drafts-controller-send-link';
import { ListingDraftsControllerSendLink$Params } from '../fn/listing-drafts/listing-drafts-controller-send-link';

@Injectable({ providedIn: 'root' })
export class ListingDraftsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listingDraftsControllerCreate()` */
  static readonly ListingDraftsControllerCreatePath = '/api/v1/listing-drafts';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listingDraftsControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  listingDraftsControllerCreate$Response(params: ListingDraftsControllerCreate$Params, context?: HttpContext): Promise<StrictHttpResponse<ListingDraftCreatedDto>> {
    const obs = listingDraftsControllerCreate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listingDraftsControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  listingDraftsControllerCreate(params: ListingDraftsControllerCreate$Params, context?: HttpContext): Promise<ListingDraftCreatedDto> {
    const resp = this.listingDraftsControllerCreate$Response(params, context);
    return resp.then((r: StrictHttpResponse<ListingDraftCreatedDto>): ListingDraftCreatedDto => r.body);
  }

  /** Path part for operation `listingDraftsControllerCurrent()` */
  static readonly ListingDraftsControllerCurrentPath = '/api/v1/listing-drafts/current';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listingDraftsControllerCurrent()` instead.
   *
   * This method doesn't expect any request body.
   */
  listingDraftsControllerCurrent$Response(params: ListingDraftsControllerCurrent$Params, context?: HttpContext): Promise<StrictHttpResponse<ListingDraftDto>> {
    const obs = listingDraftsControllerCurrent(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listingDraftsControllerCurrent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listingDraftsControllerCurrent(params: ListingDraftsControllerCurrent$Params, context?: HttpContext): Promise<ListingDraftDto> {
    const resp = this.listingDraftsControllerCurrent$Response(params, context);
    return resp.then((r: StrictHttpResponse<ListingDraftDto>): ListingDraftDto => r.body);
  }

  /** Path part for operation `listingDraftsControllerSave()` */
  static readonly ListingDraftsControllerSavePath = '/api/v1/listing-drafts/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listingDraftsControllerSave()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  listingDraftsControllerSave$Response(params: ListingDraftsControllerSave$Params, context?: HttpContext): Promise<StrictHttpResponse<ListingDraftSavedDto>> {
    const obs = listingDraftsControllerSave(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listingDraftsControllerSave$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  listingDraftsControllerSave(params: ListingDraftsControllerSave$Params, context?: HttpContext): Promise<ListingDraftSavedDto> {
    const resp = this.listingDraftsControllerSave$Response(params, context);
    return resp.then((r: StrictHttpResponse<ListingDraftSavedDto>): ListingDraftSavedDto => r.body);
  }

  /** Path part for operation `listingDraftsControllerSendLink()` */
  static readonly ListingDraftsControllerSendLinkPath = '/api/v1/listing-drafts/{id}/continue-link';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listingDraftsControllerSendLink()` instead.
   *
   * This method doesn't expect any request body.
   */
  listingDraftsControllerSendLink$Response(params: ListingDraftsControllerSendLink$Params, context?: HttpContext): Promise<StrictHttpResponse<ContinueLinkSentDto>> {
    const obs = listingDraftsControllerSendLink(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listingDraftsControllerSendLink$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listingDraftsControllerSendLink(params: ListingDraftsControllerSendLink$Params, context?: HttpContext): Promise<ContinueLinkSentDto> {
    const resp = this.listingDraftsControllerSendLink$Response(params, context);
    return resp.then((r: StrictHttpResponse<ContinueLinkSentDto>): ContinueLinkSentDto => r.body);
  }

}
