/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { liveControllerLive } from '../fn/live/live-controller-live';
import { LiveControllerLive$Params } from '../fn/live/live-controller-live';
import { liveControllerTest } from '../fn/live/live-controller-test';
import { LiveControllerTest$Params } from '../fn/live/live-controller-test';

@Injectable({ providedIn: 'root' })
export class LiveService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `liveControllerLive()` */
  static readonly LiveControllerLivePath = '/api/v1/live';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `liveControllerLive()` instead.
   *
   * This method doesn't expect any request body.
   */
  liveControllerLive$Response(params?: LiveControllerLive$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = liveControllerLive(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `liveControllerLive$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  liveControllerLive(params?: LiveControllerLive$Params, context?: HttpContext): Promise<void> {
    const resp = this.liveControllerLive$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `liveControllerTest()` */
  static readonly LiveControllerTestPath = '/api/v1/admin/live/test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `liveControllerTest()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  liveControllerTest$Response(params: LiveControllerTest$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = liveControllerTest(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `liveControllerTest$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  liveControllerTest(params: LiveControllerTest$Params, context?: HttpContext): Promise<void> {
    const resp = this.liveControllerTest$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
