/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { meControllerMe } from '../fn/me/me-controller-me';
import { MeControllerMe$Params } from '../fn/me/me-controller-me';
import { MeDto } from '../models/me-dto';

@Injectable({ providedIn: 'root' })
export class MeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `meControllerMe()` */
  static readonly MeControllerMePath = '/api/v1/me';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `meControllerMe()` instead.
   *
   * This method doesn't expect any request body.
   */
  meControllerMe$Response(params?: MeControllerMe$Params, context?: HttpContext): Promise<StrictHttpResponse<MeDto>> {
    const obs = meControllerMe(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `meControllerMe$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  meControllerMe(params?: MeControllerMe$Params, context?: HttpContext): Promise<MeDto> {
    const resp = this.meControllerMe$Response(params, context);
    return resp.then((r: StrictHttpResponse<MeDto>): MeDto => r.body);
  }

}
