/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { bellControllerList } from '../fn/notifications/bell-controller-list';
import { BellControllerList$Params } from '../fn/notifications/bell-controller-list';
import { bellControllerRead } from '../fn/notifications/bell-controller-read';
import { BellControllerRead$Params } from '../fn/notifications/bell-controller-read';
import { bellControllerReadAll } from '../fn/notifications/bell-controller-read-all';
import { BellControllerReadAll$Params } from '../fn/notifications/bell-controller-read-all';
import { bellControllerUnreadCount } from '../fn/notifications/bell-controller-unread-count';
import { BellControllerUnreadCount$Params } from '../fn/notifications/bell-controller-unread-count';
import { newsControllerSend } from '../fn/notifications/news-controller-send';
import { NewsControllerSend$Params } from '../fn/notifications/news-controller-send';
import { newsControllerUnsubscribe } from '../fn/notifications/news-controller-unsubscribe';
import { NewsControllerUnsubscribe$Params } from '../fn/notifications/news-controller-unsubscribe';
import { NewsSentDto } from '../models/news-sent-dto';
import { NotificationDto } from '../models/notification-dto';
import { NotificationPageDto } from '../models/notification-page-dto';
import { notificationPreferencesControllerRead } from '../fn/notifications/notification-preferences-controller-read';
import { NotificationPreferencesControllerRead$Params } from '../fn/notifications/notification-preferences-controller-read';
import { notificationPreferencesControllerSave } from '../fn/notifications/notification-preferences-controller-save';
import { NotificationPreferencesControllerSave$Params } from '../fn/notifications/notification-preferences-controller-save';
import { NotificationPreferencesDto } from '../models/notification-preferences-dto';
import { notificationsControllerTest } from '../fn/notifications/notifications-controller-test';
import { NotificationsControllerTest$Params } from '../fn/notifications/notifications-controller-test';
import { PushKeyDto } from '../models/push-key-dto';
import { PushSubscriptionDto } from '../models/push-subscription-dto';
import { pushSubscriptionsControllerKey } from '../fn/notifications/push-subscriptions-controller-key';
import { PushSubscriptionsControllerKey$Params } from '../fn/notifications/push-subscriptions-controller-key';
import { pushSubscriptionsControllerRemove } from '../fn/notifications/push-subscriptions-controller-remove';
import { PushSubscriptionsControllerRemove$Params } from '../fn/notifications/push-subscriptions-controller-remove';
import { pushSubscriptionsControllerSave } from '../fn/notifications/push-subscriptions-controller-save';
import { PushSubscriptionsControllerSave$Params } from '../fn/notifications/push-subscriptions-controller-save';
import { pushSubscriptionsControllerTest } from '../fn/notifications/push-subscriptions-controller-test';
import { PushSubscriptionsControllerTest$Params } from '../fn/notifications/push-subscriptions-controller-test';
import { PushTestQueuedDto } from '../models/push-test-queued-dto';
import { TestMessageQueuedDto } from '../models/test-message-queued-dto';
import { UnreadCountDto } from '../models/unread-count-dto';

@Injectable({ providedIn: 'root' })
export class NotificationsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `bellControllerList()` */
  static readonly BellControllerListPath = '/api/v1/notifications';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bellControllerList()` instead.
   *
   * This method doesn't expect any request body.
   */
  bellControllerList$Response(params?: BellControllerList$Params, context?: HttpContext): Promise<StrictHttpResponse<NotificationPageDto>> {
    const obs = bellControllerList(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bellControllerList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bellControllerList(params?: BellControllerList$Params, context?: HttpContext): Promise<NotificationPageDto> {
    const resp = this.bellControllerList$Response(params, context);
    return resp.then((r: StrictHttpResponse<NotificationPageDto>): NotificationPageDto => r.body);
  }

  /** Path part for operation `bellControllerUnreadCount()` */
  static readonly BellControllerUnreadCountPath = '/api/v1/notifications/unread-count';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bellControllerUnreadCount()` instead.
   *
   * This method doesn't expect any request body.
   */
  bellControllerUnreadCount$Response(params?: BellControllerUnreadCount$Params, context?: HttpContext): Promise<StrictHttpResponse<UnreadCountDto>> {
    const obs = bellControllerUnreadCount(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bellControllerUnreadCount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bellControllerUnreadCount(params?: BellControllerUnreadCount$Params, context?: HttpContext): Promise<UnreadCountDto> {
    const resp = this.bellControllerUnreadCount$Response(params, context);
    return resp.then((r: StrictHttpResponse<UnreadCountDto>): UnreadCountDto => r.body);
  }

  /** Path part for operation `bellControllerReadAll()` */
  static readonly BellControllerReadAllPath = '/api/v1/notifications/read-all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bellControllerReadAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  bellControllerReadAll$Response(params?: BellControllerReadAll$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = bellControllerReadAll(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bellControllerReadAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bellControllerReadAll(params?: BellControllerReadAll$Params, context?: HttpContext): Promise<void> {
    const resp = this.bellControllerReadAll$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `bellControllerRead()` */
  static readonly BellControllerReadPath = '/api/v1/notifications/{id}/read';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bellControllerRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  bellControllerRead$Response(params: BellControllerRead$Params, context?: HttpContext): Promise<StrictHttpResponse<NotificationDto>> {
    const obs = bellControllerRead(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bellControllerRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bellControllerRead(params: BellControllerRead$Params, context?: HttpContext): Promise<NotificationDto> {
    const resp = this.bellControllerRead$Response(params, context);
    return resp.then((r: StrictHttpResponse<NotificationDto>): NotificationDto => r.body);
  }

  /** Path part for operation `notificationsControllerTest()` */
  static readonly NotificationsControllerTestPath = '/api/v1/admin/notifications/test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerTest()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  notificationsControllerTest$Response(params: NotificationsControllerTest$Params, context?: HttpContext): Promise<StrictHttpResponse<TestMessageQueuedDto>> {
    const obs = notificationsControllerTest(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerTest$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  notificationsControllerTest(params: NotificationsControllerTest$Params, context?: HttpContext): Promise<TestMessageQueuedDto> {
    const resp = this.notificationsControllerTest$Response(params, context);
    return resp.then((r: StrictHttpResponse<TestMessageQueuedDto>): TestMessageQueuedDto => r.body);
  }

  /** Path part for operation `notificationPreferencesControllerRead()` */
  static readonly NotificationPreferencesControllerReadPath = '/api/v1/notification-preferences';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationPreferencesControllerRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationPreferencesControllerRead$Response(params?: NotificationPreferencesControllerRead$Params, context?: HttpContext): Promise<StrictHttpResponse<NotificationPreferencesDto>> {
    const obs = notificationPreferencesControllerRead(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationPreferencesControllerRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationPreferencesControllerRead(params?: NotificationPreferencesControllerRead$Params, context?: HttpContext): Promise<NotificationPreferencesDto> {
    const resp = this.notificationPreferencesControllerRead$Response(params, context);
    return resp.then((r: StrictHttpResponse<NotificationPreferencesDto>): NotificationPreferencesDto => r.body);
  }

  /** Path part for operation `notificationPreferencesControllerSave()` */
  static readonly NotificationPreferencesControllerSavePath = '/api/v1/notification-preferences';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationPreferencesControllerSave()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  notificationPreferencesControllerSave$Response(params: NotificationPreferencesControllerSave$Params, context?: HttpContext): Promise<StrictHttpResponse<NotificationPreferencesDto>> {
    const obs = notificationPreferencesControllerSave(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationPreferencesControllerSave$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  notificationPreferencesControllerSave(params: NotificationPreferencesControllerSave$Params, context?: HttpContext): Promise<NotificationPreferencesDto> {
    const resp = this.notificationPreferencesControllerSave$Response(params, context);
    return resp.then((r: StrictHttpResponse<NotificationPreferencesDto>): NotificationPreferencesDto => r.body);
  }

  /** Path part for operation `newsControllerUnsubscribe()` */
  static readonly NewsControllerUnsubscribePath = '/api/v1/notification-preferences/unsubscribe';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `newsControllerUnsubscribe()` instead.
   *
   * This method doesn't expect any request body.
   */
  newsControllerUnsubscribe$Response(params: NewsControllerUnsubscribe$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = newsControllerUnsubscribe(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `newsControllerUnsubscribe$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  newsControllerUnsubscribe(params: NewsControllerUnsubscribe$Params, context?: HttpContext): Promise<void> {
    const resp = this.newsControllerUnsubscribe$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `newsControllerSend()` */
  static readonly NewsControllerSendPath = '/api/v1/admin/news';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `newsControllerSend()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  newsControllerSend$Response(params: NewsControllerSend$Params, context?: HttpContext): Promise<StrictHttpResponse<NewsSentDto>> {
    const obs = newsControllerSend(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `newsControllerSend$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  newsControllerSend(params: NewsControllerSend$Params, context?: HttpContext): Promise<NewsSentDto> {
    const resp = this.newsControllerSend$Response(params, context);
    return resp.then((r: StrictHttpResponse<NewsSentDto>): NewsSentDto => r.body);
  }

  /** Path part for operation `pushSubscriptionsControllerKey()` */
  static readonly PushSubscriptionsControllerKeyPath = '/api/v1/push-subscriptions/key';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `pushSubscriptionsControllerKey()` instead.
   *
   * This method doesn't expect any request body.
   */
  pushSubscriptionsControllerKey$Response(params?: PushSubscriptionsControllerKey$Params, context?: HttpContext): Promise<StrictHttpResponse<PushKeyDto>> {
    const obs = pushSubscriptionsControllerKey(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `pushSubscriptionsControllerKey$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  pushSubscriptionsControllerKey(params?: PushSubscriptionsControllerKey$Params, context?: HttpContext): Promise<PushKeyDto> {
    const resp = this.pushSubscriptionsControllerKey$Response(params, context);
    return resp.then((r: StrictHttpResponse<PushKeyDto>): PushKeyDto => r.body);
  }

  /** Path part for operation `pushSubscriptionsControllerSave()` */
  static readonly PushSubscriptionsControllerSavePath = '/api/v1/push-subscriptions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `pushSubscriptionsControllerSave()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  pushSubscriptionsControllerSave$Response(params: PushSubscriptionsControllerSave$Params, context?: HttpContext): Promise<StrictHttpResponse<PushSubscriptionDto>> {
    const obs = pushSubscriptionsControllerSave(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `pushSubscriptionsControllerSave$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  pushSubscriptionsControllerSave(params: PushSubscriptionsControllerSave$Params, context?: HttpContext): Promise<PushSubscriptionDto> {
    const resp = this.pushSubscriptionsControllerSave$Response(params, context);
    return resp.then((r: StrictHttpResponse<PushSubscriptionDto>): PushSubscriptionDto => r.body);
  }

  /** Path part for operation `pushSubscriptionsControllerTest()` */
  static readonly PushSubscriptionsControllerTestPath = '/api/v1/push-subscriptions/test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `pushSubscriptionsControllerTest()` instead.
   *
   * This method doesn't expect any request body.
   */
  pushSubscriptionsControllerTest$Response(params?: PushSubscriptionsControllerTest$Params, context?: HttpContext): Promise<StrictHttpResponse<PushTestQueuedDto>> {
    const obs = pushSubscriptionsControllerTest(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `pushSubscriptionsControllerTest$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  pushSubscriptionsControllerTest(params?: PushSubscriptionsControllerTest$Params, context?: HttpContext): Promise<PushTestQueuedDto> {
    const resp = this.pushSubscriptionsControllerTest$Response(params, context);
    return resp.then((r: StrictHttpResponse<PushTestQueuedDto>): PushTestQueuedDto => r.body);
  }

  /** Path part for operation `pushSubscriptionsControllerRemove()` */
  static readonly PushSubscriptionsControllerRemovePath = '/api/v1/push-subscriptions/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `pushSubscriptionsControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  pushSubscriptionsControllerRemove$Response(params: PushSubscriptionsControllerRemove$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = pushSubscriptionsControllerRemove(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `pushSubscriptionsControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  pushSubscriptionsControllerRemove(params: PushSubscriptionsControllerRemove$Params, context?: HttpContext): Promise<void> {
    const resp = this.pushSubscriptionsControllerRemove$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
