/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { newsControllerSend } from '../fn/notifications/news-controller-send';
import { NewsControllerSend$Params } from '../fn/notifications/news-controller-send';
import { newsControllerUnsubscribe } from '../fn/notifications/news-controller-unsubscribe';
import { NewsControllerUnsubscribe$Params } from '../fn/notifications/news-controller-unsubscribe';
import { NewsSentDto } from '../models/news-sent-dto';
import { notificationPreferencesControllerRead } from '../fn/notifications/notification-preferences-controller-read';
import { NotificationPreferencesControllerRead$Params } from '../fn/notifications/notification-preferences-controller-read';
import { notificationPreferencesControllerSave } from '../fn/notifications/notification-preferences-controller-save';
import { NotificationPreferencesControllerSave$Params } from '../fn/notifications/notification-preferences-controller-save';
import { NotificationPreferencesDto } from '../models/notification-preferences-dto';
import { notificationsControllerTest } from '../fn/notifications/notifications-controller-test';
import { NotificationsControllerTest$Params } from '../fn/notifications/notifications-controller-test';
import { TestMessageQueuedDto } from '../models/test-message-queued-dto';

@Injectable({ providedIn: 'root' })
export class NotificationsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `notificationsControllerTest()` */
  static readonly NotificationsControllerTestPath = '/api/v1/admin/notifications/test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerTest()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  notificationsControllerTest$Response(params: NotificationsControllerTest$Params, context?: HttpContext): Promise<StrictHttpResponse<TestMessageQueuedDto>> {
    const obs = notificationsControllerTest(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerTest$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  notificationsControllerTest(params: NotificationsControllerTest$Params, context?: HttpContext): Promise<TestMessageQueuedDto> {
    const resp = this.notificationsControllerTest$Response(params, context);
    return resp.then((r: StrictHttpResponse<TestMessageQueuedDto>): TestMessageQueuedDto => r.body);
  }

  /** Path part for operation `notificationPreferencesControllerRead()` */
  static readonly NotificationPreferencesControllerReadPath = '/api/v1/notification-preferences';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationPreferencesControllerRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationPreferencesControllerRead$Response(params?: NotificationPreferencesControllerRead$Params, context?: HttpContext): Promise<StrictHttpResponse<NotificationPreferencesDto>> {
    const obs = notificationPreferencesControllerRead(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationPreferencesControllerRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationPreferencesControllerRead(params?: NotificationPreferencesControllerRead$Params, context?: HttpContext): Promise<NotificationPreferencesDto> {
    const resp = this.notificationPreferencesControllerRead$Response(params, context);
    return resp.then((r: StrictHttpResponse<NotificationPreferencesDto>): NotificationPreferencesDto => r.body);
  }

  /** Path part for operation `notificationPreferencesControllerSave()` */
  static readonly NotificationPreferencesControllerSavePath = '/api/v1/notification-preferences';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationPreferencesControllerSave()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  notificationPreferencesControllerSave$Response(params: NotificationPreferencesControllerSave$Params, context?: HttpContext): Promise<StrictHttpResponse<NotificationPreferencesDto>> {
    const obs = notificationPreferencesControllerSave(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationPreferencesControllerSave$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  notificationPreferencesControllerSave(params: NotificationPreferencesControllerSave$Params, context?: HttpContext): Promise<NotificationPreferencesDto> {
    const resp = this.notificationPreferencesControllerSave$Response(params, context);
    return resp.then((r: StrictHttpResponse<NotificationPreferencesDto>): NotificationPreferencesDto => r.body);
  }

  /** Path part for operation `newsControllerUnsubscribe()` */
  static readonly NewsControllerUnsubscribePath = '/api/v1/notification-preferences/unsubscribe';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `newsControllerUnsubscribe()` instead.
   *
   * This method doesn't expect any request body.
   */
  newsControllerUnsubscribe$Response(params: NewsControllerUnsubscribe$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = newsControllerUnsubscribe(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `newsControllerUnsubscribe$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  newsControllerUnsubscribe(params: NewsControllerUnsubscribe$Params, context?: HttpContext): Promise<void> {
    const resp = this.newsControllerUnsubscribe$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `newsControllerSend()` */
  static readonly NewsControllerSendPath = '/api/v1/admin/news';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `newsControllerSend()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  newsControllerSend$Response(params: NewsControllerSend$Params, context?: HttpContext): Promise<StrictHttpResponse<NewsSentDto>> {
    const obs = newsControllerSend(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `newsControllerSend$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  newsControllerSend(params: NewsControllerSend$Params, context?: HttpContext): Promise<NewsSentDto> {
    const resp = this.newsControllerSend$Response(params, context);
    return resp.then((r: StrictHttpResponse<NewsSentDto>): NewsSentDto => r.body);
  }

}
