/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { placesControllerSearch } from '../fn/places/places-controller-search';
import { PlacesControllerSearch$Params } from '../fn/places/places-controller-search';
import { PlacesResultDto } from '../models/places-result-dto';

@Injectable({ providedIn: 'root' })
export class PlacesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `placesControllerSearch()` */
  static readonly PlacesControllerSearchPath = '/api/v1/places';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `placesControllerSearch()` instead.
   *
   * This method doesn't expect any request body.
   */
  placesControllerSearch$Response(params: PlacesControllerSearch$Params, context?: HttpContext): Promise<StrictHttpResponse<PlacesResultDto>> {
    const obs = placesControllerSearch(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `placesControllerSearch$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  placesControllerSearch(params: PlacesControllerSearch$Params, context?: HttpContext): Promise<PlacesResultDto> {
    const resp = this.placesControllerSearch$Response(params, context);
    return resp.then((r: StrictHttpResponse<PlacesResultDto>): PlacesResultDto => r.body);
  }

}
