/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { platformStatusControllerStatus } from '../fn/platform/platform-status-controller-status';
import { PlatformStatusControllerStatus$Params } from '../fn/platform/platform-status-controller-status';
import { PlatformStatusDto } from '../models/platform-status-dto';

@Injectable({ providedIn: 'root' })
export class PlatformService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `platformStatusControllerStatus()` */
  static readonly PlatformStatusControllerStatusPath = '/api/v1/platform-status';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `platformStatusControllerStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  platformStatusControllerStatus$Response(params?: PlatformStatusControllerStatus$Params, context?: HttpContext): Promise<StrictHttpResponse<PlatformStatusDto>> {
    const obs = platformStatusControllerStatus(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `platformStatusControllerStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  platformStatusControllerStatus(params?: PlatformStatusControllerStatus$Params, context?: HttpContext): Promise<PlatformStatusDto> {
    const resp = this.platformStatusControllerStatus$Response(params, context);
    return resp.then((r: StrictHttpResponse<PlatformStatusDto>): PlatformStatusDto => r.body);
  }

}
