/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { PublicHolidayDto } from '../models/public-holiday-dto';
import { publicHolidaysControllerList } from '../fn/public-holidays/public-holidays-controller-list';
import { PublicHolidaysControllerList$Params } from '../fn/public-holidays/public-holidays-controller-list';

@Injectable({ providedIn: 'root' })
export class PublicHolidaysService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `publicHolidaysControllerList()` */
  static readonly PublicHolidaysControllerListPath = '/api/v1/public-holidays';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicHolidaysControllerList()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicHolidaysControllerList$Response(params: PublicHolidaysControllerList$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<PublicHolidayDto>>> {
    const obs = publicHolidaysControllerList(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicHolidaysControllerList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicHolidaysControllerList(params: PublicHolidaysControllerList$Params, context?: HttpContext): Promise<Array<PublicHolidayDto>> {
    const resp = this.publicHolidaysControllerList$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<PublicHolidayDto>>): Array<PublicHolidayDto> => r.body);
  }

}
