/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CandidateGarageListDto } from '../models/candidate-garage-list-dto';
import { quoteRequestsControllerCandidates } from '../fn/quote-requests/quote-requests-controller-candidates';
import { QuoteRequestsControllerCandidates$Params } from '../fn/quote-requests/quote-requests-controller-candidates';
import { quoteRequestsControllerSend } from '../fn/quote-requests/quote-requests-controller-send';
import { QuoteRequestsControllerSend$Params } from '../fn/quote-requests/quote-requests-controller-send';
import { RequestDto } from '../models/request-dto';

@Injectable({ providedIn: 'root' })
export class QuoteRequestsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `quoteRequestsControllerSend()` */
  static readonly QuoteRequestsControllerSendPath = '/api/v1/quote-requests';

  /**
   * Send a quote request to up to five garages.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `quoteRequestsControllerSend()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  quoteRequestsControllerSend$Response(params: QuoteRequestsControllerSend$Params, context?: HttpContext): Promise<StrictHttpResponse<RequestDto>> {
    const obs = quoteRequestsControllerSend(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Send a quote request to up to five garages.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `quoteRequestsControllerSend$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  quoteRequestsControllerSend(params: QuoteRequestsControllerSend$Params, context?: HttpContext): Promise<RequestDto> {
    const resp = this.quoteRequestsControllerSend$Response(params, context);
    return resp.then((r: StrictHttpResponse<RequestDto>): RequestDto => r.body);
  }

  /** Path part for operation `quoteRequestsControllerCandidates()` */
  static readonly QuoteRequestsControllerCandidatesPath = '/api/v1/quote-requests/garages';

  /**
   * Up to five more garages near a place that would take the request.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `quoteRequestsControllerCandidates()` instead.
   *
   * This method doesn't expect any request body.
   */
  quoteRequestsControllerCandidates$Response(params: QuoteRequestsControllerCandidates$Params, context?: HttpContext): Promise<StrictHttpResponse<CandidateGarageListDto>> {
    const obs = quoteRequestsControllerCandidates(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Up to five more garages near a place that would take the request.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `quoteRequestsControllerCandidates$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  quoteRequestsControllerCandidates(params: QuoteRequestsControllerCandidates$Params, context?: HttpContext): Promise<CandidateGarageListDto> {
    const resp = this.quoteRequestsControllerCandidates$Response(params, context);
    return resp.then((r: StrictHttpResponse<CandidateGarageListDto>): CandidateGarageListDto => r.body);
  }

}
