/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { GarageQuoteDto } from '../models/garage-quote-dto';
import { quotesControllerSend } from '../fn/quotes/quotes-controller-send';
import { QuotesControllerSend$Params } from '../fn/quotes/quotes-controller-send';

@Injectable({ providedIn: 'root' })
export class QuotesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `quotesControllerSend()` */
  static readonly QuotesControllerSendPath = '/api/v1/quotes';

  /**
   * Send the garage’s quote for a request.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `quotesControllerSend()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  quotesControllerSend$Response(params: QuotesControllerSend$Params, context?: HttpContext): Promise<StrictHttpResponse<GarageQuoteDto>> {
    const obs = quotesControllerSend(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Send the garage’s quote for a request.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `quotesControllerSend$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  quotesControllerSend(params: QuotesControllerSend$Params, context?: HttpContext): Promise<GarageQuoteDto> {
    const resp = this.quotesControllerSend$Response(params, context);
    return resp.then((r: StrictHttpResponse<GarageQuoteDto>): GarageQuoteDto => r.body);
  }

}
