/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { RequestDto } from '../models/request-dto';
import { RequestListDto } from '../models/request-list-dto';
import { requestsControllerGet } from '../fn/requests/requests-controller-get';
import { RequestsControllerGet$Params } from '../fn/requests/requests-controller-get';
import { requestsControllerList } from '../fn/requests/requests-controller-list';
import { RequestsControllerList$Params } from '../fn/requests/requests-controller-list';

@Injectable({ providedIn: 'root' })
export class RequestsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `requestsControllerList()` */
  static readonly RequestsControllerListPath = '/api/v1/requests';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `requestsControllerList()` instead.
   *
   * This method doesn't expect any request body.
   */
  requestsControllerList$Response(params?: RequestsControllerList$Params, context?: HttpContext): Promise<StrictHttpResponse<RequestListDto>> {
    const obs = requestsControllerList(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `requestsControllerList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  requestsControllerList(params?: RequestsControllerList$Params, context?: HttpContext): Promise<RequestListDto> {
    const resp = this.requestsControllerList$Response(params, context);
    return resp.then((r: StrictHttpResponse<RequestListDto>): RequestListDto => r.body);
  }

  /** Path part for operation `requestsControllerGet()` */
  static readonly RequestsControllerGetPath = '/api/v1/requests/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `requestsControllerGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  requestsControllerGet$Response(params: RequestsControllerGet$Params, context?: HttpContext): Promise<StrictHttpResponse<RequestDto>> {
    const obs = requestsControllerGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `requestsControllerGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  requestsControllerGet(params: RequestsControllerGet$Params, context?: HttpContext): Promise<RequestDto> {
    const resp = this.requestsControllerGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<RequestDto>): RequestDto => r.body);
  }

}
