/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { garageSearchControllerForBrand } from '../fn/search/garage-search-controller-for-brand';
import { GarageSearchControllerForBrand$Params } from '../fn/search/garage-search-controller-for-brand';
import { GarageSearchPageDto } from '../models/garage-search-page-dto';

@Injectable({ providedIn: 'root' })
export class SearchService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `garageSearchControllerForBrand()` */
  static readonly GarageSearchControllerForBrandPath = '/api/v1/search/garages';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `garageSearchControllerForBrand()` instead.
   *
   * This method doesn't expect any request body.
   */
  garageSearchControllerForBrand$Response(params: GarageSearchControllerForBrand$Params, context?: HttpContext): Promise<StrictHttpResponse<GarageSearchPageDto>> {
    const obs = garageSearchControllerForBrand(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `garageSearchControllerForBrand$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  garageSearchControllerForBrand(params: GarageSearchControllerForBrand$Params, context?: HttpContext): Promise<GarageSearchPageDto> {
    const resp = this.garageSearchControllerForBrand$Response(params, context);
    return resp.then((r: StrictHttpResponse<GarageSearchPageDto>): GarageSearchPageDto => r.body);
  }

}
