/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { DocumentPageAddressDto } from '../models/document-page-address-dto';
import { legalDocumentsControllerPageAddress } from '../fn/verification-documents/legal-documents-controller-page-address';
import { LegalDocumentsControllerPageAddress$Params } from '../fn/verification-documents/legal-documents-controller-page-address';

@Injectable({ providedIn: 'root' })
export class VerificationDocumentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `legalDocumentsControllerPageAddress()` */
  static readonly LegalDocumentsControllerPageAddressPath = '/api/v1/admin/verification-files/{id}/documents/{documentId}/pages/{n}/download-url';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `legalDocumentsControllerPageAddress()` instead.
   *
   * This method doesn't expect any request body.
   */
  legalDocumentsControllerPageAddress$Response(params: LegalDocumentsControllerPageAddress$Params, context?: HttpContext): Promise<StrictHttpResponse<DocumentPageAddressDto>> {
    const obs = legalDocumentsControllerPageAddress(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `legalDocumentsControllerPageAddress$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  legalDocumentsControllerPageAddress(params: LegalDocumentsControllerPageAddress$Params, context?: HttpContext): Promise<DocumentPageAddressDto> {
    const resp = this.legalDocumentsControllerPageAddress$Response(params, context);
    return resp.then((r: StrictHttpResponse<DocumentPageAddressDto>): DocumentPageAddressDto => r.body);
  }

}
