/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicHolidayDto } from '../../models/public-holiday-dto';

export interface PublicHolidaysControllerList$Params {
  year: number;
}

export function publicHolidaysControllerList(http: HttpClient, rootUrl: string, params: PublicHolidaysControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PublicHolidayDto>>> {
  const rb = new RequestBuilder(rootUrl, publicHolidaysControllerList.PATH, 'get');
  if (params) {
    rb.query('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PublicHolidayDto>>;
    })
  );
}

publicHolidaysControllerList.PATH = '/api/v1/public-holidays';
