/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BrandPageDto } from '../../models/brand-page-dto';

export interface BrandsControllerSearch$Params {

/**
 * Part of a brand name; accents and case are ignored
 */
  q?: string;

/**
 * The nextCursor of the previous page
 */
  cursor?: string;
}

export function brandsControllerSearch(http: HttpClient, rootUrl: string, params?: BrandsControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<BrandPageDto>> {
  const rb = new RequestBuilder(rootUrl, brandsControllerSearch.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
    rb.query('cursor', params.cursor, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BrandPageDto>;
    })
  );
}

brandsControllerSearch.PATH = '/api/v1/brands';
