/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GarageQuoteDto } from '../../models/garage-quote-dto';
import { SendQuoteDto } from '../../models/send-quote-dto';

export interface QuotesControllerSend$Params {

/**
 * One per send the garage means; a repeat answers the first quote
 */
  'Idempotency-Key': string;
      body: SendQuoteDto
}

export function quotesControllerSend(http: HttpClient, rootUrl: string, params: QuotesControllerSend$Params, context?: HttpContext): Observable<StrictHttpResponse<GarageQuoteDto>> {
  const rb = new RequestBuilder(rootUrl, quotesControllerSend.PATH, 'post');
  if (params) {
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GarageQuoteDto>;
    })
  );
}

quotesControllerSend.PATH = '/api/v1/quotes';
