/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailChangeDto } from '../../models/email-change-dto';
import { PendingEmailDto } from '../../models/pending-email-dto';

export interface EmailChangeControllerRequest$Params {
      body: EmailChangeDto
}

export function emailChangeControllerRequest(http: HttpClient, rootUrl: string, params: EmailChangeControllerRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<PendingEmailDto>> {
  const rb = new RequestBuilder(rootUrl, emailChangeControllerRequest.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PendingEmailDto>;
    })
  );
}

emailChangeControllerRequest.PATH = '/api/v1/me/email';
