/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MeDto } from '../../models/me-dto';
import { PhoneConfirmDto } from '../../models/phone-confirm-dto';

export interface PhoneChangeControllerConfirm$Params {
      body: PhoneConfirmDto
}

export function phoneChangeControllerConfirm(http: HttpClient, rootUrl: string, params: PhoneChangeControllerConfirm$Params, context?: HttpContext): Observable<StrictHttpResponse<MeDto>> {
  const rb = new RequestBuilder(rootUrl, phoneChangeControllerConfirm.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MeDto>;
    })
  );
}

phoneChangeControllerConfirm.PATH = '/api/v1/me/phone/confirm';
