/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateGarageReportDto } from '../../models/create-garage-report-dto';
import { GarageReportCreatedDto } from '../../models/garage-report-created-dto';

export interface GarageReportsControllerReport$Params {
  id: string;
      body: CreateGarageReportDto
}

export function garageReportsControllerReport(http: HttpClient, rootUrl: string, params: GarageReportsControllerReport$Params, context?: HttpContext): Observable<StrictHttpResponse<GarageReportCreatedDto>> {
  const rb = new RequestBuilder(rootUrl, garageReportsControllerReport.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GarageReportCreatedDto>;
    })
  );
}

garageReportsControllerReport.PATH = '/api/v1/garages/{id}/reports';
