/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GarageSettingsDto } from '../../models/garage-settings-dto';
import { UpdateGarageDto } from '../../models/update-garage-dto';

export interface GarageSettingsControllerUpdate$Params {
  garageId: string;
      body: UpdateGarageDto
}

export function garageSettingsControllerUpdate(http: HttpClient, rootUrl: string, params: GarageSettingsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<GarageSettingsDto>> {
  const rb = new RequestBuilder(rootUrl, garageSettingsControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('garageId', params.garageId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GarageSettingsDto>;
    })
  );
}

garageSettingsControllerUpdate.PATH = '/api/v1/garages/{garageId}';
