/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StaffInviteDto } from '../../models/staff-invite-dto';
import { StaffInviteSentDto } from '../../models/staff-invite-sent-dto';

export interface GarageInvitesControllerSend$Params {
  garageId: string;
      body: StaffInviteDto
}

export function garageInvitesControllerSend(http: HttpClient, rootUrl: string, params: GarageInvitesControllerSend$Params, context?: HttpContext): Observable<StrictHttpResponse<StaffInviteSentDto>> {
  const rb = new RequestBuilder(rootUrl, garageInvitesControllerSend.PATH, 'post');
  if (params) {
    rb.path('garageId', params.garageId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StaffInviteSentDto>;
    })
  );
}

garageInvitesControllerSend.PATH = '/api/v1/garages/{garageId}/invites';
