/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StaffInviteSentDto } from '../../models/staff-invite-sent-dto';

export interface GarageInvitesControllerResend$Params {
  garageId: string;
  id: string;
}

export function garageInvitesControllerResend(http: HttpClient, rootUrl: string, params: GarageInvitesControllerResend$Params, context?: HttpContext): Observable<StrictHttpResponse<StaffInviteSentDto>> {
  const rb = new RequestBuilder(rootUrl, garageInvitesControllerResend.PATH, 'post');
  if (params) {
    rb.path('garageId', params.garageId, {});
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StaffInviteSentDto>;
    })
  );
}

garageInvitesControllerResend.PATH = '/api/v1/garages/{garageId}/invites/{id}/resend';
