/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GarageBrandAnswerDto } from '../../models/garage-brand-answer-dto';
import { ReplaceGarageBrandsDto } from '../../models/replace-garage-brands-dto';

export interface GarageBrandsControllerReplace$Params {
  garageId: string;
      body: ReplaceGarageBrandsDto
}

export function garageBrandsControllerReplace(http: HttpClient, rootUrl: string, params: GarageBrandsControllerReplace$Params, context?: HttpContext): Observable<StrictHttpResponse<GarageBrandAnswerDto>> {
  const rb = new RequestBuilder(rootUrl, garageBrandsControllerReplace.PATH, 'put');
  if (params) {
    rb.path('garageId', params.garageId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GarageBrandAnswerDto>;
    })
  );
}

garageBrandsControllerReplace.PATH = '/api/v1/garages/{garageId}/brands';
