/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PriceListDto } from '../../models/price-list-dto';

export interface PriceListControllerRead$Params {
  garageId: string;
}

export function priceListControllerRead(http: HttpClient, rootUrl: string, params: PriceListControllerRead$Params, context?: HttpContext): Observable<StrictHttpResponse<PriceListDto>> {
  const rb = new RequestBuilder(rootUrl, priceListControllerRead.PATH, 'get');
  if (params) {
    rb.path('garageId', params.garageId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PriceListDto>;
    })
  );
}

priceListControllerRead.PATH = '/api/v1/garages/{garageId}/prices';
