/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicGarageDto } from '../../models/public-garage-dto';

export interface PublicGaragesControllerBySlug$Params {
  slug: string;
}

export function publicGaragesControllerBySlug(http: HttpClient, rootUrl: string, params: PublicGaragesControllerBySlug$Params, context?: HttpContext): Observable<StrictHttpResponse<PublicGarageDto>> {
  const rb = new RequestBuilder(rootUrl, publicGaragesControllerBySlug.PATH, 'get');
  if (params) {
    rb.path('slug', params.slug, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublicGarageDto>;
    })
  );
}

publicGaragesControllerBySlug.PATH = '/api/v1/garages/{slug}';
