// Passwords of 8 or more characters that lead the public breach lists
// (SecLists, Passwords/Common-Credentials/10k-most-common.txt, in its order),
// and the Romanian ones built on "parola" and the product's name. Lower case.
export const COMMON_PASSWORDS: ReadonlySet<string> = new Set([
  'password',
  '12345678',
  '123456789',
  '1234567890',
  'baseball',
  'football',
  'qwertyuiop',
  'iloveyou',
  'trustno1',
  'superman',
  'sunshine',
  'princess',
  'starwars',
  'whatever',
  'computer',
  'michelle',
  'jennifer',
  'corvette',
  'mercedes',
  'internet',
  'samantha',
  'midnight',
  'mustang1',
  'password1',
  'password12',
  'password123',
  'passw0rd',
  'p@ssw0rd',
  'qwerty123',
  'qwertyui',
  '1q2w3e4r',
  '1qaz2wsx',
  'zaq12wsx',
  'asdfghjkl',
  'abcd1234',
  'abc12345',
  '11111111',
  '00000000',
  '88888888',
  '87654321',
  '12341234',
  '11223344',
  'aaaaaaaa',
  'letmein1',
  'welcome1',
  'changeme',
  'iloveyou1',
  'football1',
  'baseball1',
  'parola123',
  'parola1234',
  'parolamea',
  'parolanoua',
  'parolaparola',
  'motorfix',
  'motorfix1',
  'motorfix123',
  'bucuresti',
  'romania1',
  'romania123',
]);

export function isCommonPassword(password: string): boolean {
  return COMMON_PASSWORDS.has(password.toLowerCase());
}
