/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JobTypeListDto } from '../../models/job-type-list-dto';

export interface JobTypesControllerSearch$Params {

/**
 * Part of a job name; accents and case are ignored
 */
  q?: string;

/**
 * Comma-separated job keys; answers those jobs only, past the first 20
 */
  keys?: string;

/**
 * Comma-separated job ids, 50 at most; answers those jobs only, past the first 20
 */
  ids?: string;
}

export function jobTypesControllerSearch(http: HttpClient, rootUrl: string, params?: JobTypesControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<JobTypeListDto>> {
  const rb = new RequestBuilder(rootUrl, jobTypesControllerSearch.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
    rb.query('keys', params.keys, {});
    rb.query('ids', params.ids, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JobTypeListDto>;
    })
  );
}

jobTypesControllerSearch.PATH = '/api/v1/job-types';
