/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentUploadAddressDto } from '../../models/document-upload-address-dto';
import { DocumentUploadRequestDto } from '../../models/document-upload-request-dto';

export interface ListingDocumentsControllerUploadAddress$Params {
  id: string;
  kind: string;
  'x-listing-token': string;
      body: DocumentUploadRequestDto
}

export function listingDocumentsControllerUploadAddress(http: HttpClient, rootUrl: string, params: ListingDocumentsControllerUploadAddress$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentUploadAddressDto>> {
  const rb = new RequestBuilder(rootUrl, listingDocumentsControllerUploadAddress.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('kind', params.kind, {});
    rb.header('x-listing-token', params['x-listing-token'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentUploadAddressDto>;
    })
  );
}

listingDocumentsControllerUploadAddress.PATH = '/api/v1/listing-drafts/{id}/documents/{kind}/upload-url';
