/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ListingDocumentsControllerRemove$Params {
  id: string;
  kind: string;
  key: string;
  'x-listing-token': string;
}

export function listingDocumentsControllerRemove(http: HttpClient, rootUrl: string, params: ListingDocumentsControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, listingDocumentsControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('kind', params.kind, {});
    rb.path('key', params.key, {});
    rb.header('x-listing-token', params['x-listing-token'], {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

listingDocumentsControllerRemove.PATH = '/api/v1/listing-drafts/{id}/documents/{kind}/{key}';
