/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfirmPhotoDto } from '../../models/confirm-photo-dto';
import { ListingPhotoDto } from '../../models/listing-photo-dto';

export interface ListingPhotosControllerConfirm$Params {
  id: string;
  'x-listing-token': string;
      body: ConfirmPhotoDto
}

export function listingPhotosControllerConfirm(http: HttpClient, rootUrl: string, params: ListingPhotosControllerConfirm$Params, context?: HttpContext): Observable<StrictHttpResponse<ListingPhotoDto>> {
  const rb = new RequestBuilder(rootUrl, listingPhotosControllerConfirm.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('x-listing-token', params['x-listing-token'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListingPhotoDto>;
    })
  );
}

listingPhotosControllerConfirm.PATH = '/api/v1/listing-drafts/{id}/photos';
