/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListingPhotosDto } from '../../models/listing-photos-dto';

export interface ListingPhotosControllerList$Params {
  id: string;
  'x-listing-token': string;
}

export function listingPhotosControllerList(http: HttpClient, rootUrl: string, params: ListingPhotosControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<ListingPhotosDto>> {
  const rb = new RequestBuilder(rootUrl, listingPhotosControllerList.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('x-listing-token', params['x-listing-token'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListingPhotosDto>;
    })
  );
}

listingPhotosControllerList.PATH = '/api/v1/listing-drafts/{id}/photos';
