/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfirmDocumentPageDto } from '../../models/confirm-document-page-dto';
import { DraftDocumentDto } from '../../models/draft-document-dto';

export interface ListingDocumentsControllerConfirm$Params {
  id: string;
  kind: string;
  'x-listing-token': string;
      body: ConfirmDocumentPageDto
}

export function listingDocumentsControllerConfirm(http: HttpClient, rootUrl: string, params: ListingDocumentsControllerConfirm$Params, context?: HttpContext): Observable<StrictHttpResponse<DraftDocumentDto>> {
  const rb = new RequestBuilder(rootUrl, listingDocumentsControllerConfirm.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('kind', params.kind, {});
    rb.header('x-listing-token', params['x-listing-token'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DraftDocumentDto>;
    })
  );
}

listingDocumentsControllerConfirm.PATH = '/api/v1/listing-drafts/{id}/documents/{kind}';
