/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListingDraftSavedDto } from '../../models/listing-draft-saved-dto';
import { SaveListingDraftDto } from '../../models/save-listing-draft-dto';

export interface ListingDraftsControllerSave$Params {
  id: string;
  'x-listing-token': string;
      body: SaveListingDraftDto
}

export function listingDraftsControllerSave(http: HttpClient, rootUrl: string, params: ListingDraftsControllerSave$Params, context?: HttpContext): Observable<StrictHttpResponse<ListingDraftSavedDto>> {
  const rb = new RequestBuilder(rootUrl, listingDraftsControllerSave.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('x-listing-token', params['x-listing-token'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListingDraftSavedDto>;
    })
  );
}

listingDraftsControllerSave.PATH = '/api/v1/listing-drafts/{id}';
