/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateListingDraftDto } from '../../models/create-listing-draft-dto';
import { ListingDraftCreatedDto } from '../../models/listing-draft-created-dto';

export interface ListingDraftsControllerCreate$Params {
      body: CreateListingDraftDto
}

export function listingDraftsControllerCreate(http: HttpClient, rootUrl: string, params: ListingDraftsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ListingDraftCreatedDto>> {
  const rb = new RequestBuilder(rootUrl, listingDraftsControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListingDraftCreatedDto>;
    })
  );
}

listingDraftsControllerCreate.PATH = '/api/v1/listing-drafts';
