/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListingDraftDto } from '../../models/listing-draft-dto';

export interface ListingDraftsControllerCurrent$Params {
  'x-listing-token': string;
  'X-Listing-Token': string;
}

export function listingDraftsControllerCurrent(http: HttpClient, rootUrl: string, params: ListingDraftsControllerCurrent$Params, context?: HttpContext): Observable<StrictHttpResponse<ListingDraftDto>> {
  const rb = new RequestBuilder(rootUrl, listingDraftsControllerCurrent.PATH, 'get');
  if (params) {
    rb.header('x-listing-token', params['x-listing-token'], {});
    rb.header('X-Listing-Token', params['X-Listing-Token'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListingDraftDto>;
    })
  );
}

listingDraftsControllerCurrent.PATH = '/api/v1/listing-drafts/current';
