/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContinueLinkSentDto } from '../../models/continue-link-sent-dto';

export interface ListingDraftsControllerSendLink$Params {
  id: string;
  'x-listing-token': string;
  'X-Listing-Token': string;
}

export function listingDraftsControllerSendLink(http: HttpClient, rootUrl: string, params: ListingDraftsControllerSendLink$Params, context?: HttpContext): Observable<StrictHttpResponse<ContinueLinkSentDto>> {
  const rb = new RequestBuilder(rootUrl, listingDraftsControllerSendLink.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('x-listing-token', params['x-listing-token'], {});
    rb.header('X-Listing-Token', params['X-Listing-Token'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContinueLinkSentDto>;
    })
  );
}

listingDraftsControllerSendLink.PATH = '/api/v1/listing-drafts/{id}/continue-link';
