/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PhotoUploadAddressDto } from '../../models/photo-upload-address-dto';
import { PhotoUploadRequestDto } from '../../models/photo-upload-request-dto';

export interface ListingPhotosControllerUploadAddress$Params {
  id: string;
  'x-listing-token': string;
      body: PhotoUploadRequestDto
}

export function listingPhotosControllerUploadAddress(http: HttpClient, rootUrl: string, params: ListingPhotosControllerUploadAddress$Params, context?: HttpContext): Observable<StrictHttpResponse<PhotoUploadAddressDto>> {
  const rb = new RequestBuilder(rootUrl, listingPhotosControllerUploadAddress.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('x-listing-token', params['x-listing-token'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PhotoUploadAddressDto>;
    })
  );
}

listingPhotosControllerUploadAddress.PATH = '/api/v1/listing-drafts/{id}/photos/upload-url';
