/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RequestDto } from '../../models/request-dto';

export interface RequestsControllerGet$Params {
  id: string;
}

export function requestsControllerGet(http: HttpClient, rootUrl: string, params: RequestsControllerGet$Params, context?: HttpContext): Observable<StrictHttpResponse<RequestDto>> {
  const rb = new RequestBuilder(rootUrl, requestsControllerGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RequestDto>;
    })
  );
}

requestsControllerGet.PATH = '/api/v1/requests/{id}';
