/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConsentRecordedDto } from '../../models/consent-recorded-dto';
import { RecordConsentDto } from '../../models/record-consent-dto';

export interface ConsentsControllerRecordMine$Params {
      body: RecordConsentDto
}

export function consentsControllerRecordMine(http: HttpClient, rootUrl: string, params: ConsentsControllerRecordMine$Params, context?: HttpContext): Observable<StrictHttpResponse<ConsentRecordedDto>> {
  const rb = new RequestBuilder(rootUrl, consentsControllerRecordMine.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConsentRecordedDto>;
    })
  );
}

consentsControllerRecordMine.PATH = '/api/v1/me/consents';
