/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MyConsentsDto } from '../../models/my-consents-dto';

export interface ConsentsControllerMine$Params {
}

export function consentsControllerMine(http: HttpClient, rootUrl: string, params?: ConsentsControllerMine$Params, context?: HttpContext): Observable<StrictHttpResponse<MyConsentsDto>> {
  const rb = new RequestBuilder(rootUrl, consentsControllerMine.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MyConsentsDto>;
    })
  );
}

consentsControllerMine.PATH = '/api/v1/me/consents';
