/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AssistantTokenDto } from '../../models/assistant-token-dto';
import { AssistantTokensDto } from '../../models/assistant-tokens-dto';

export interface AssistantControllerToken$XWwwFormUrlencoded$Params {
      body: AssistantTokenDto
}

export function assistantControllerToken$XWwwFormUrlencoded(http: HttpClient, rootUrl: string, params: AssistantControllerToken$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<AssistantTokensDto>> {
  const rb = new RequestBuilder(rootUrl, assistantControllerToken$XWwwFormUrlencoded.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AssistantTokensDto>;
    })
  );
}

assistantControllerToken$XWwwFormUrlencoded.PATH = '/api/v1/auth/assistant/token';
