/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AssistantControllerAuthorize$Params {
  scope?: any;
  nonce: any;
  state: any;
  response_type: 'code';
  redirect_uri: any;
  client_id: any;
}

export function assistantControllerAuthorize(http: HttpClient, rootUrl: string, params: AssistantControllerAuthorize$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, assistantControllerAuthorize.PATH, 'get');
  if (params) {
    rb.query('scope', params.scope, {});
    rb.query('nonce', params.nonce, {});
    rb.query('state', params.state, {});
    rb.query('response_type', params.response_type, {});
    rb.query('redirect_uri', params.redirect_uri, {});
    rb.query('client_id', params.client_id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

assistantControllerAuthorize.PATH = '/api/v1/auth/assistant/authorize';
