/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OAuthPendingDto } from '../../models/o-auth-pending-dto';

export interface OauthControllerPending$Params {
}

export function oauthControllerPending(http: HttpClient, rootUrl: string, params?: OauthControllerPending$Params, context?: HttpContext): Observable<StrictHttpResponse<OAuthPendingDto>> {
  const rb = new RequestBuilder(rootUrl, oauthControllerPending.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OAuthPendingDto>;
    })
  );
}

oauthControllerPending.PATH = '/api/v1/auth/oauth/pending';
