/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface OauthControllerStartGoogle$Params {
  remember?: boolean;
  language?: 'ro' | 'en';
}

export function oauthControllerStartGoogle(http: HttpClient, rootUrl: string, params?: OauthControllerStartGoogle$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, oauthControllerStartGoogle.PATH, 'get');
  if (params) {
    rb.query('remember', params.remember, {});
    rb.query('language', params.language, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

oauthControllerStartGoogle.PATH = '/api/v1/auth/oauth/google';
