/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProvidersDto } from '../../models/providers-dto';

export interface OauthControllerProviders$Params {
}

export function oauthControllerProviders(http: HttpClient, rootUrl: string, params?: OauthControllerProviders$Params, context?: HttpContext): Observable<StrictHttpResponse<ProvidersDto>> {
  const rb = new RequestBuilder(rootUrl, oauthControllerProviders.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProvidersDto>;
    })
  );
}

oauthControllerProviders.PATH = '/api/v1/auth/providers';
