/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PhoneSessionDto } from '../../models/phone-session-dto';
import { PhoneSignInDto } from '../../models/phone-sign-in-dto';

export interface PhoneSignInControllerPhoneSignIn$Params {
      body: PhoneSignInDto
}

export function phoneSignInControllerPhoneSignIn(http: HttpClient, rootUrl: string, params: PhoneSignInControllerPhoneSignIn$Params, context?: HttpContext): Observable<StrictHttpResponse<PhoneSessionDto>> {
  const rb = new RequestBuilder(rootUrl, phoneSignInControllerPhoneSignIn.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PhoneSessionDto>;
    })
  );
}

phoneSignInControllerPhoneSignIn.PATH = '/api/v1/auth/phone-sign-in';
