/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { HealthControllerLive$Params as HealthControllerLive$Params } from './fn/health/health-controller-live';
export { healthControllerLive as healthControllerLive } from './fn/health/health-controller-live';
export type { HealthControllerReady$Params as HealthControllerReady$Params } from './fn/health/health-controller-ready';
export { healthControllerReady as healthControllerReady } from './fn/health/health-controller-ready';
