/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { HealthChecksDto } from './models/health-checks-dto';
export type { HealthLiveDto } from './models/health-live-dto';
export type { HealthReadyDto } from './models/health-ready-dto';
