/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AcceptedTextDto {
  acceptedAt: string;
  kind: 'terms' | 'privacy_notice';
  language: 'ro' | 'en';
  textVersion: string;
}
