/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminAccountDto } from '../models/admin-account-dto';
export interface AdminAccountsPageDto {

  /**
   * Newest first, 20 at most
   */
  items: Array<AdminAccountDto>;
  nextCursor: string | null;

  /**
   * Every account the search and filters match, counted at this read; only when q, role or status is given
   */
  total?: number;
}
