/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminCityDto } from '../models/admin-city-dto';
export interface AdminOverviewDto {

  /**
   * Active driver accounts used in the last 30 days
   */
  activeDrivers: number;

  /**
   * Active drivers on the 1st of the current month, absent when that night was not recorded
   */
  activeDriversMonthStart?: number;

  /**
   * Active drivers on the first day of the chosen period, absent for today, a city or a night not recorded
   */
  activeDriversPeriodStart?: number;

  /**
   * The whole country first, then every city with a listed garage, most garages first
   */
  cities: Array<AdminCityDto>;

  /**
   * Verification files submitted or in review of garages in the chosen city; only with a city
   */
  cityGaragesWaiting?: number;

  /**
   * Listed garages first approved in the chosen period; only with a period
   */
  garagesApprovedInPeriod?: number;

  /**
   * Listed garages first approved in the current Europe/Bucharest month
   */
  garagesApprovedThisMonth: number;

  /**
   * Garages approved and listed now
   */
  garagesListed: number;

  /**
   * Verification files submitted or in review, on the whole platform
   */
  garagesWaiting: number;

  /**
   * The MotorFix overview dashboard in Grafana for this API's environment, absent when Grafana is not configured
   */
  observabilityUrl?: string;
}
