/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminGrowthMonthDto } from '../models/admin-growth-month-dto';
export interface AdminGrowthDto {
  months: Array<AdminGrowthMonthDto>;
}
