/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminCityDto {

  /**
   * Garages approved and listed now in the city
   */
  garages: number;
  key: string;
  name: string;
}
