/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminGrowthMonthDto } from '../models/admin-growth-month-dto';
export interface AdminGrowthDto {

  /**
   * The last twelve months, oldest first, ending with the current one
   */
  months: Array<AdminGrowthMonthDto>;
}
