/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminGrowthMonthDto {

  /**
   * Active drivers at the month’s close, live for the current month; absent when the close was not recorded
   */
  activeDrivers?: number;

  /**
   * Garages listed at the month’s close, live for the current month; absent when the close was not recorded
   */
  garagesListed?: number;

  /**
   * The Europe/Bucharest month
   */
  month: string;
}
