/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminAccountCountDto {

  /**
   * requests for a driver, reviews for a garage or mechanic, age in days for a receptionist, an admin or an account under 7 days old
   */
  kind: 'requests' | 'reviews' | 'age';
  value: number;
}
