/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminAccountsSummaryDto {

  /**
   * Active driver accounts used in the last 30 days
   */
  activeDrivers: number;

  /**
   * Garages approved and listed now
   */
  garagesListed: number;

  /**
   * Mechanic cards with an account at listed garages
   */
  mechanics: number;
}
