/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminAccountCountDto } from '../models/admin-account-count-dto';
export interface AdminAccountDto {

  /**
   * Cars not removed
   */
  carsCount: number;
  count: AdminAccountCountDto;
  createdAt: string;

  /**
   * The garage of the first role: owned, worked at as receptionist, or of the mechanic card
   */
  garageName: string | null;
  id: string;
  name: string;

  /**
   * In the order driver, garage, receptionist, mechanic, admin
   */
  roles: Array<'driver' | 'garage' | 'receptionist' | 'mechanic' | 'admin'>;

  /**
   * When the state began: creation for active, the last recorded suspension for suspended (null when none is recorded)
   */
  since: string | null;
  status: 'active' | 'suspended';
}
