/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AnalyticsConsentDto {
  at: string;
  decision: 'granted' | 'refused' | 'withdrawn';
  language: 'ro' | 'en';
  textVersion: string;
}
