/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApproveAssistantSignInDto {

  /**
   * The signed hand-off from the connect page address
   */
  request: string;
}
