/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssistantTokenDto {
  client_id?: string;
  client_secret?: string;
  code?: string;

  /**
   * Sent when the identity server uses PKCE; not checked
   */
  code_verifier?: string;
  grant_type?: string;
  redirect_uri?: string;
}
