/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssistantApprovalDto {

  /**
   * The identity server's address, with the code and the state
   */
  redirect: string;
}
