/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssistantTokensDto {

  /**
   * The same token as id_token
   */
  access_token: string;
  expires_in: number;

  /**
   * HS256, signed with the client secret
   */
  id_token: string;
  token_type: 'Bearer';
}
