/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuditActorDto {
  id: string | null;

  /**
   * First name, or "MotorFix" for the system
   */
  name: string;
  role: 'driver' | 'owner' | 'receptionist' | 'mechanic' | 'admin' | 'system';
}
