/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditActorDto } from '../models/audit-actor-dto';
export interface AuditEntryDto {
  action: 'create' | 'update' | 'delete' | 'open';
  actor: AuditActorDto;
  at: string;
  carId: string | null;
  field: string | null;
  garageId: string | null;
  id: string;

  /**
   * Never shown to the driver
   */
  internal: boolean;
  jobId: string | null;
  kind: string | null;

  /**
   * The value as stored (money in bani, times in UTC)
   */
  newValue: ((string | number | boolean | {
} | Array<any>)) | null;

  /**
   * The value as stored (money in bani, times in UTC)
   */
  oldValue: ((string | number | boolean | {
} | Array<any>)) | null;
  subjectId: string;

  /**
   * The table the entry is about, e.g. quote
   */
  subjectType: string;
  text: string | null;
  viaAssistant: boolean;
}
