/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditEntryDto } from '../models/audit-entry-dto';
export interface AuditHistoryPageDto {

  /**
   * Newest first, 20 at most
   */
  items: Array<AuditEntryDto>;
  nextCursor: string | null;

  /**
   * Entries matching the filters
   */
  total: number;
}
