/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GarageRefDto } from '../models/garage-ref-dto';
export interface BookingDto {
  cancelReason: ('plans_changed' | 'found_another_garage' | 'problem_solved' | 'no_mechanic_free' | 'parts_not_available' | 'closed_that_day' | 'driver_asked' | 'other' | 'garage_suspended' | 'driver_account_closed') | null;
  cancelledAt: string | null;
  cancelledBySide: ('driver' | 'garage' | 'system') | null;
  completedAt: string | null;
  confirmBy: string;
  confirmedAt: string | null;
  createdAt: string;
  durationMinutes: number;
  garage: GarageRefDto;
  id: string;
  noShowAt: string | null;
  quoteId: string;
  startsAt: string;
  status: 'awaiting_confirmation' | 'confirmed' | 'lapsed' | 'cancelled' | 'no_show' | 'completed';
}
