/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BrandCountsDto {

  /**
   * Approved garages that refuse the brand or have not marked it, over everything found
   */
  doesNotTake: number;

  /**
   * Approved garages that work on the brand, over everything found
   */
  worksOn: number;
}
