/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BrandDto {
  id: string;
  name: string;

  /**
   * 1 is the most popular; null is unranked
   */
  popularity: number | null;
  slug: string;
}
