/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BrandDto } from '../models/brand-dto';
export interface BrandPageDto {

  /**
   * By popularity, unranked last, then by name; 20 at most
   */
  items: Array<BrandDto>;
  nextCursor: string | null;

  /**
   * Brands matching the search
   */
  total: number;
}
