/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CandidateGarageDto } from '../models/candidate-garage-dto';
export interface CandidateGarageListDto {
  items: Array<CandidateGarageDto>;
}
