/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CandidateGarageDto {

  /**
   * A mobile mechanic, who comes to the driver
   */
  comesToYou: boolean;

  /**
   * Kilometres from the place; null for a mobile mechanic
   */
  distanceKm: number | null;
  id: string;
  name: string;
  slug: string;
}
