/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CarDto {
  brandId: string;
  brandName: string;
  createdAt: string;
  engine: string | null;
  fuel: 'petrol' | 'diesel' | 'hybrid' | 'electric';
  id: string;
  itpUntil: string | null;
  model: string;
  odometerKm: number;
  plate: string | null;
  rcaUntil: string | null;
  rovinietaUntil: string | null;
  year: number;
}
