/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CarDto } from '../models/car-dto';
export interface CarListDto {

  /**
   * Newest first
   */
  items: Array<CarDto>;
}
