/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChangePlatformRuleDto {

  /**
   * The value the admin's screen showed
   */
  seen: (boolean | number | string | {
});

  /**
   * The new value
   */
  value: (boolean | number | string | {
});
}
