/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ConfirmEmailDto {

  /**
   * The token of a confirmation link: 43 base64url characters
   */
  token: string;
}
