/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CourtesyCarDto {
  paid: boolean;

  /**
   * Per day, in bani: whole lei; only when paid
   */
  pricePerDayBani?: number;
}
