/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateListingDraftDto {

  /**
   * The form data, whole every time
   */
  data: {
};

  /**
   * Trimmed and lower-cased
   */
  email: string;
  language: 'ro' | 'en';
  step: number;
}
