/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateGarageReportDto {

  /**
   * What happened, stored as written (never trimmed)
   */
  text: string;
}
