/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateQuoteRequestDto {
  carId: string;

  /**
   * Trimmed; required, of at least 10 characters, when no job is chosen
   */
  description?: string | null;

  /**
   * The garages, in the order the driver ticked them; at most 5
   */
  garageIds: Array<string>;
  jobTypeIds: Array<string>;

  /**
   * Where each garage of garageIds was chosen, one for one
   */
  sources: Array<'search' | 'map' | 'home' | 'shared_link' | 'profile_direct' | 'saved' | 'unknown'>;
}
