/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCarDto {
  brandId: string;

  /**
   * Trimmed
   */
  engine?: string;
  fuel: 'petrol' | 'diesel' | 'hybrid' | 'electric';

  /**
   * At most five years ahead
   */
  itpUntil?: string;

  /**
   * Trimmed
   */
  model: string;
  odometerKm: number;

  /**
   * Stored in upper case without spaces or hyphens
   */
  plate?: string;

  /**
   * At most five years ahead
   */
  rcaUntil?: string;

  /**
   * At most five years ahead
   */
  rovinietaUntil?: string;

  /**
   * From 1950 to next year
   */
  year: number;
}
