/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeclineRequestDto {
  reason: 'fully_booked' | 'job_not_done' | 'make_model_engine_not_done' | 'need_to_see_car';
}
