/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentPageAddressDto {
  expiresAt: string;

  /**
   * Signed for 5 minutes, opens inline
   */
  url: string;
}
