/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentUploadAddressDto {
  expiresAt: string;

  /**
   * Form fields to send before the file
   */
  fields: {
[key: string]: string;
};

  /**
   * The key to confirm once uploaded
   */
  key: string;

  /**
   * Where the browser posts the form
   */
  url: string;
}
