/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DraftDocumentDto {
  issuedOn?: string;
  kind: 'onrc_certificate' | 'rar_authorisation';

  /**
   * Storage keys in page order
   */
  pages: Array<string>;
}
