/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GarageCarDto {
  brand: string;
  engine: string | null;
  fuel: 'petrol' | 'diesel' | 'hybrid' | 'electric';
  model: string;
  plate?: string;
  year: number;
}
