/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BrandRefDto } from '../models/brand-ref-dto';
export interface GarageBrandAnswerDto {
  brandNote: string | null;
  doesNotTake: Array<BrandRefDto>;
  refusalPhrase: string | null;
  worksOn: Array<BrandRefDto>;
}
