/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CarSnapshotDto } from '../models/car-snapshot-dto';
import { DriverNameDto } from '../models/driver-name-dto';
import { GarageQuoteDto } from '../models/garage-quote-dto';
import { GarageRecipientDto } from '../models/garage-recipient-dto';
import { RequestJobDto } from '../models/request-job-dto';
export interface GarageRequestSummaryDto {
  car: CarSnapshotDto;
  createdAt: string;
  driver: DriverNameDto;
  expiresAt: string;
  id: string;
  jobs: Array<RequestJobDto>;
  quote: (GarageQuoteDto & {
}) | null;
  recipient: GarageRecipientDto;
  status: 'sent' | 'quoted' | 'booked' | 'in_work' | 'done' | 'closed';
}
