/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GarageRequestSummaryDto } from '../models/garage-request-summary-dto';
export interface GarageRequestListDto {
  items: Array<GarageRequestSummaryDto>;
  nextCursor: string | null;
  total: number;
}
