/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GaragePermissionsDto } from '../models/garage-permissions-dto';
export interface GarageAccessDto {

  /**
   * The garage’s feature switches by key; a missing key is on
   */
  features: {
[key: string]: boolean;
};
  garageId: string;
  name: string;
  permissions: GaragePermissionsDto;

  /**
   * The role at this garage
   */
  role: 'owner' | 'receptionist' | 'mechanic';
  status: 'draft' | 'approved' | 'suspended';
}
