/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GarageRequestJobPriceDto {
  durationMinutes: number | null;

  /**
   * Lower end of the price, in bani
   */
  fromBani: number;

  /**
   * Upper end of the price, in bani; null when open-ended
   */
  toBani: number | null;
}
