/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GarageDriverDto {
  phone?: string;

  /**
   * First name and the last name’s initial
   */
  shortName: string;
}
