/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GarageRequestJobDto {
  id: string;
  jobTypeId: string;
  nameEn: string;
  nameRo: string;

  /**
   * The garage ticked this job for the request's car brand
   */
  offered: boolean;
  position: number;
}
