/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GarageRequestJobPriceDto } from '../models/garage-request-job-price-dto';
export interface GarageRequestDetailJobDto {
  id: string;
  jobTypeId: string;
  nameEn: string;
  nameRo: string;

  /**
   * The garage ticked this job for the request's car brand
   */
  offered: boolean;
  position: number;
  price: (GarageRequestJobPriceDto & {
}) | null;
}
