/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CourtesyCarDto } from '../models/courtesy-car-dto';
import { PaymentMethodsDto } from '../models/payment-methods-dto';
export interface GarageSettingsDto {

  /**
   * Absent when the garage does not list the courtesy car
   */
  courtesyCar?: CourtesyCarDto;
  paymentMethods: PaymentMethodsDto;
}
