/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GarageRecipientDto {
  answeredAt: string | null;
  declineReason: ('fully_booked' | 'job_not_done' | 'make_model_engine_not_done' | 'need_to_see_car') | null;
  declinedAt: string | null;
  source: 'search' | 'map' | 'home' | 'shared_link' | 'profile_direct' | 'saved' | 'unknown';
  status: 'waiting' | 'quoted' | 'declined' | 'expired' | 'closed';
}
