/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GarageBrandStanceDto {
  brandId: string;

  /**
   * A taken brand only. Left out: unchanged, or all four for a brand taken now; empty: none
   */
  fuels?: Array<'petrol' | 'diesel' | 'hybrid' | 'electric'>;

  /**
   * A taken brand only: the jobs of the price list it is ticked for. Left out: unchanged, or every job for a brand taken now; empty: none
   */
  jobs?: Array<string>;
  stance: 'works_on' | 'does_not_take';
}
