/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BrandRefDto } from '../models/brand-ref-dto';
import { OwnerBrandDto } from '../models/owner-brand-dto';
export interface GarageBrandOwnerAnswerDto {
  brandNote: string | null;
  doesNotTake: Array<BrandRefDto>;
  refusalPhrase: string | null;
  worksOn: Array<OwnerBrandDto>;
}
