/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GaragePermissionsDto {
  canAnswerQuotes: boolean;
  canMoveBookings: boolean;
  canRecordFinalPrice: boolean;
}
