/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GarageBookingDto } from '../models/garage-booking-dto';
import { GarageCarDto } from '../models/garage-car-dto';
import { GarageDriverDto } from '../models/garage-driver-dto';
import { GarageQuoteDto } from '../models/garage-quote-dto';
import { GarageRecipientDto } from '../models/garage-recipient-dto';
import { GarageRequestJobDto } from '../models/garage-request-job-dto';
export interface GarageRequestDto {
  booking: (GarageBookingDto & {
}) | null;
  car: GarageCarDto;

  /**
   * Set with closedReason
   */
  closedAt: string | null;

  /**
   * Set on the rows of a closed read
   */
  closedReason: ('expired' | 'garage_suspended' | 'cancelled' | 'account_closed' | 'accepted_elsewhere') | null;
  createdAt: string;
  description: string | null;

  /**
   * The description's first line
   */
  descriptionLine: string | null;
  driver: GarageDriverDto;
  expiresAt: string;
  id: string;
  jobs: Array<GarageRequestJobDto>;
  quote: (GarageQuoteDto & {
}) | null;
  recipient: GarageRecipientDto;
  status: 'sent' | 'quoted' | 'booked' | 'in_work' | 'done' | 'closed';
}
