/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QuoteJobDto } from '../models/quote-job-dto';
export interface GarageQuoteDto {
  acceptedAt: string | null;
  changedAt: string | null;
  durationMinutes: number;
  expiresAt: string;

  /**
   * Lower end of the price, in bani
   */
  fromBani: number;
  id: string;
  jobs: Array<QuoteJobDto>;
  note: string | null;
  sentAt: string;

  /**
   * The proposed start
   */
  slot: string;
  status: 'waiting' | 'accepted' | 'withdrawn' | 'expired' | 'lost' | 'declined_by_driver';

  /**
   * Upper end of the price, in bani
   */
  toBani: number;
  withdrawnAt: string | null;
}
