/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GarageBookingDto } from '../models/garage-booking-dto';
import { GarageCarDto } from '../models/garage-car-dto';
import { GarageDriverDto } from '../models/garage-driver-dto';
import { GarageQuoteDto } from '../models/garage-quote-dto';
import { GarageRecipientDto } from '../models/garage-recipient-dto';
import { RequestJobDto } from '../models/request-job-dto';
export interface GarageRequestDto {
  booking: (GarageBookingDto & {
}) | null;
  car: GarageCarDto;
  createdAt: string;
  description: string | null;
  driver: GarageDriverDto;
  expiresAt: string;
  id: string;
  jobs: Array<RequestJobDto>;
  quote: (GarageQuoteDto & {
}) | null;
  recipient: GarageRecipientDto;
  status: 'sent' | 'quoted' | 'booked' | 'in_work' | 'done' | 'closed';
}
