/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BrandCountsDto } from '../models/brand-counts-dto';
import { ListedGarageDto } from '../models/listed-garage-dto';
export interface GarageSearchPageDto {
  counts: BrandCountsDto;

  /**
   * Garages that work on the brand first, then the rest; inside a group by name, then id; 20 at most
   */
  items: Array<ListedGarageDto>;
  nextCursor: string | null;

  /**
   * Every approved garage: worksOn + doesNotTake
   */
  total: number;
}
