/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HealthChecksDto } from '../models/health-checks-dto';
export interface HealthReadyDto {
  checks: HealthChecksDto;
  status: 'ok' | 'error';

  /**
   * The deployed commit SHA, or dev
   */
  version: string;
}
