/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BrandDto } from '../models/brand-dto';
export interface HomeDto {
  brand: BrandDto;

  /**
   * Approved garages that work on the brand
   */
  takers: number;

  /**
   * Approved garages, in the area of the place when one is given
   */
  total: number;
}
