/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BrandDto } from '../models/brand-dto';
import { HomeGarageDto } from '../models/home-garage-dto';
export interface HomeDto {

  /**
   * The best-rated garage that works on the brand in the area; null when none does
   */
  best: (HomeGarageDto & {
}) | null;
  brand: BrandDto;

  /**
   * Up to three: the two best takers, then the best garage that refuses or never said; with no taker, up to three of those
   */
  preview: Array<HomeGarageDto>;

  /**
   * Approved garages that work on the brand
   */
  takers: number;

  /**
   * Approved garages, in the area of the place when one is given
   */
  total: number;
}
