/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HomeGarageDto {
  businessKind: ('company' | 'pfa' | 'ii' | 'mobile') | null;

  /**
   * The address's city; never for a mobile mechanic, absent when unknown
   */
  city?: string;

  /**
   * True for a mobile mechanic whose area holds the place. Only with near
   */
  comesToYou?: boolean;

  /**
   * Km from the place, one decimal; null for a mobile mechanic. Only with near
   */
  distanceKm?: number | null;
  id: string;

  /**
   * The hourly labour price it starts from, in whole lei
   */
  labourFromLei: number | null;
  name: string;

  /**
   * One decimal, 1.0 to 5.0; null until the garage has reviews
   */
  rating: number | null;
  reviewCount: number;
  slug: string;

  /**
   * The garage's answer for the brand; unstated when it has not marked it
   */
  stance: 'works_on' | 'does_not_take' | 'unstated';
}
