/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InviteViewDto {

  /**
   * The invited address
   */
  email: string;

  /**
   * The garage name, as typed by its owner
   */
  garage: string;
  kind: 'mechanic' | 'receptionist';

  /**
   * The invitee's name, as the owner typed it
   */
  name: string;
}
