/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JobSummaryDto } from '../models/job-summary-dto';
export interface JobListDto {
  items: Array<JobSummaryDto>;
  nextCursor: string | null;
  total: number;
}
