/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface JobStepDto {
  customerLabel: string | null;
  doneAt: string | null;
  id: string;
  label: string;
  position: number;
}
