/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JobTypeDto } from '../models/job-type-dto';
export interface JobTypeListDto {

  /**
   * Approved jobs by Romanian name; 20 at most for a search, every one named by keys or ids
   */
  items: Array<JobTypeDto>;
}
