/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DriverNameDto } from '../models/driver-name-dto';
import { GarageCarDto } from '../models/garage-car-dto';
export interface JobSummaryDto {
  bookingId: string;
  car: GarageCarDto;
  createdAt: string;
  driver: DriverNameDto;
  etaAt: string | null;
  finishedAt: string | null;
  handedOverAt: string | null;
  id: string;
  mechanicId: string | null;
  pausedAt: string | null;
  startedAt: string | null;
  status: 'to_do' | 'in_work' | 'paused' | 'done' | 'cancelled';
}
