/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface JobStageEntryDto {
  actorRole: 'driver' | 'owner' | 'receptionist' | 'mechanic' | 'admin' | 'system';
  at: string;
  fromStatus: ('to_do' | 'in_work' | 'paused' | 'done' | 'cancelled') | null;
  id: string;
  text: string | null;
  toStatus: 'to_do' | 'in_work' | 'paused' | 'done' | 'cancelled';
}
