/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DriverNameDto } from '../models/driver-name-dto';
import { GarageCarDto } from '../models/garage-car-dto';
import { JobStageEntryDto } from '../models/job-stage-entry-dto';
import { JobStepDto } from '../models/job-step-dto';
export interface JobDto {
  bookingId: string;
  car: GarageCarDto;
  createdAt: string;
  driver: DriverNameDto;
  etaAt: string | null;
  finalPriceBani: number | null;
  finishedAt: string | null;
  handedOverAt: string | null;
  id: string;
  mechanicId: string | null;
  pausedAt: string | null;
  stages: Array<JobStageEntryDto>;
  startedAt: string | null;
  status: 'to_do' | 'in_work' | 'paused' | 'done' | 'cancelled';
  steps: Array<JobStepDto>;
}
