/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ListingPhotoDto {
  height?: number;
  key: string;

  /**
   * 0 is the cover
   */
  position: number;

  /**
   * Whether the thumbnail is ready
   */
  processed: boolean;

  /**
   * Signed for 5 minutes
   */
  thumbnailUrl?: string;
  width?: number;
}
