/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ListingPhotoDto } from '../models/listing-photo-dto';
export interface ListingPhotosDto {
  photos: Array<ListingPhotoDto>;
}
