/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ListingDraftDto {
  data: {
};
  email: string;
  id: string;
  language: 'ro' | 'en';
  status: 'open' | 'submitted';
  step: number;
  updatedAt: string;
}
