/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BrandRefDto } from '../models/brand-ref-dto';
export interface ListedGarageDto {
  brandNote: string | null;

  /**
   * True for a mobile mechanic whose area holds the place. Only with near
   */
  comesToYou?: boolean;

  /**
   * Km from the place, one decimal; null for a mobile mechanic. Only with near
   */
  distanceKm?: number | null;
  doesNotTake: Array<BrandRefDto>;
  id: string;
  name: string;
  refusalPhrase: string | null;
  slug: string;

  /**
   * The garage's answer for the brand; unstated when it has not marked it
   */
  stance: 'works_on' | 'does_not_take' | 'unstated';
  worksOn: Array<BrandRefDto>;
}
