/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ListedGarageDto {
  id: string;
  name: string;
  slug: string;

  /**
   * The garage's answer for the brand; unstated when it has not marked it
   */
  stance: 'works_on' | 'does_not_take' | 'unstated';
}
