/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MeDto {

  /**
   * What the role in use may do
   */
  capabilities: Array<string>;
  email: string | null;

  /**
   * Whether the e-mail is confirmed; false when there is none
   */
  emailConfirmed: boolean;
  garageId: string | null;
  id: string;
  landing: '/app/driver' | '/app/garage' | '/app/admin';
  language: 'ro' | 'en';
  name: string;

  /**
   * The role in use
   */
  role: 'driver' | 'garage' | 'receptionist' | 'mechanic' | 'admin';
  roles: Array<'driver' | 'garage' | 'receptionist' | 'mechanic' | 'admin'>;
}
