/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GarageAccessDto } from '../models/garage-access-dto';
export interface MeDto {

  /**
   * What the role in use may do
   */
  capabilities: Array<string>;

  /**
   * The city saved in Setări
   */
  city: string | null;
  email: string | null;

  /**
   * Whether the e-mail is confirmed; false when there is none
   */
  emailConfirmed: boolean;

  /**
   * The garages the account works at; empty with none
   */
  garageAccess: Array<GarageAccessDto>;
  garageId: string | null;
  id: string;
  landing: '/app/driver' | '/app/garage' | '/app/admin';
  language: 'ro' | 'en';
  name: string;

  /**
   * The role in use
   */
  role: 'driver' | 'garage' | 'receptionist' | 'mechanic' | 'admin';
  roles: Array<'driver' | 'garage' | 'receptionist' | 'mechanic' | 'admin'>;
}
