/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AcceptedTextDto } from '../models/accepted-text-dto';
import { AnalyticsConsentDto } from '../models/analytics-consent-dto';
export interface MyConsentsDto {

  /**
   * The latest accepted version of each text
   */
  accepted: Array<AcceptedTextDto>;

  /**
   * The analytics choice with the latest time; null when none
   */
  analytics: (AnalyticsConsentDto & {
}) | null;
}
