/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NewsConsentDto {

  /**
   * The version to show, and send back on saving
   */
  currentTextVersion: string;
  givenAt: string | null;
  state: 'none' | 'given' | 'withdrawn';

  /**
   * The consent text version the driver confirmed
   */
  textVersion: string | null;
  withdrawnAt: string | null;
}
