/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationDto {
  at: string;
  id: string;

  /**
   * A catalogue type, e.g. QUOTE_RECEIVED
   */
  kind: string;

  /**
   * The driver view the row opens, e.g. /app/driver/cars/<id>; null when it opens nothing
   */
  link: string | null;
  readAt: string | null;

  /**
   * The object it is about
   */
  subjectId: string | null;

  /**
   * Rendered in the language asked
   */
  text: string;
}
