/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NotificationDto } from '../models/notification-dto';
export interface NotificationPageDto {
  items: Array<NotificationDto>;
  nextCursor: string | null;
}
