/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NewsConsentDto } from '../models/news-consent-dto';
import { NotificationGroupDto } from '../models/notification-group-dto';
import { NotificationPreferenceDto } from '../models/notification-preference-dto';
export interface NotificationPreferencesDto {
  groups: Array<NotificationGroupDto>;
  newsConsent: NewsConsentDto;
  preferences: Array<NotificationPreferenceDto>;
}
