/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationGroupDto {
  enabled: boolean;
  key: 'offers' | 'bookings' | 'due_dates' | 'news' | 'reviews_history';

  /**
   * The notification types the switch covers
   */
  types: Array<string>;
}
