/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationPreferenceDto {

  /**
   * Sent whatever the person chooses
   */
  alwaysSent: boolean;
  channel: 'email' | 'push' | 'sms' | 'whatsapp';
  enabled: boolean;

  /**
   * The garage of a staff choice; null for a personal one
   */
  garageId: string | null;

  /**
   * A notification type, e.g. QUOTE_RECEIVED
   */
  type: string;
}
