/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NotificationGroupDto } from '../models/notification-group-dto';
import { NotificationPreferenceDto } from '../models/notification-preference-dto';
export interface NotificationPreferencesDto {
  groups: Array<NotificationGroupDto>;
  preferences: Array<NotificationPreferenceDto>;
}
