/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ConsentDto } from '../models/consent-dto';
export interface OAuthCompleteDto {

  /**
   * The current terms and privacy versions; without them the answer is 400 consent_required
   */
  consent?: ConsentDto;

  /**
   * The interface language
   */
  language: 'ro' | 'en';

  /**
   * Trimmed
   */
  name: string;
}
