/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OAuthPendingDto {

  /**
   * The e-mail the provider gave
   */
  email?: string;

  /**
   * The name the provider gave; may be empty
   */
  name: string;
  provider: 'google' | 'apple';
}
