/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OwnerBrandDto {
  id: string;

  /**
   * Ticked job type ids, in price-list order
   */
  jobs: Array<string>;
  name: string;
  slug: string;
}
