/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PasswordChangeDto {

  /**
   * Required when the account already has a password
   */
  currentPassword?: string;

  /**
   * 8 to 128 characters, not a common password
   */
  newPassword: string;
}
