/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PasswordResetCompleteDto {

  /**
   * 8 to 128 characters, not a common password
   */
  password: string;

  /**
   * The token of a reset link: the link's last part
   */
  token: string;
}
