/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PasswordResetCheckDto {

  /**
   * The token of a reset link: the link's last part
   */
  token: string;
}
