/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PhoneChangeDto {

  /**
   * As typed: spaces, dots, dashes and brackets dropped, 00 and a national 0 read as +40; must then be E.164
   */
  phone: string;
}
