/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ConsentDto } from '../models/consent-dto';
export interface PhoneSignInDto {

  /**
   * The six digits sent by WhatsApp
   */
  code: string;

  /**
   * The current terms and privacy versions; required with the name
   */
  consent?: ConsentDto;

  /**
   * A new account's language
   */
  language?: 'ro' | 'en';

  /**
   * Trimmed; with consent, creates an account for a new number
   */
  name?: string;

  /**
   * As typed: spaces, dots, dashes and brackets dropped, 00 and a national 0 read as +40; must then be E.164
   */
  phone: string;

  /**
   * Keep the session after the browser closes
   */
  remember?: boolean;
}
