/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PhoneSessionDto {

  /**
   * Bearer token, valid 15 minutes; keep it in memory
   */
  accessToken?: string;

  /**
   * No account holds the number: send the name and consent
   */
  next?: 'profile';
}
