/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlaceSuggestionDto {
  label: string;
  lat: number;
  lng: number;

  /**
   * The town or city, when the provider knows it
   */
  locality?: string;
}
