/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PlatformRuleChangeDto } from '../models/platform-rule-change-dto';
export interface PlatformRuleChangesDto {

  /**
   * The last five decided, newest first
   */
  decided: Array<PlatformRuleChangeDto>;
  waiting: (PlatformRuleChangeDto & {
}) | null;
}
