/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlatformRuleChangeDto {
  decidedAt: string | null;
  decidedByName: string | null;
  id: string;
  key: string;

  /**
   * The caller asked it
   */
  mine: boolean;
  reason: string;
  requestedAt: string;

  /**
   * The asker's first name
   */
  requestedByName: string;
  status: 'requested' | 'approved' | 'refused' | 'cancelled';
}
