/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlatformRuleDto {
  defaultValue: (boolean | number | string | {
});
  key: string;

  /**
   * Switching it off needs a second admin
   */
  requiresTwoAdmins: boolean;
  updatedAt: string | null;
  updatedBy: string | null;
  value: (boolean | number | string | {
});
}
