/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PlatformRuleDto } from '../models/platform-rule-dto';
export interface PlatformRulesDto {

  /**
   * The server runs in production
   */
  production: boolean;
  rules: Array<PlatformRuleDto>;
}
