/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PriceListItemDto } from '../models/price-list-item-dto';
export interface PriceListDto {

  /**
   * Every job of the garage's price list, once, in the list's order; empty without one
   */
  items: Array<PriceListItemDto>;
}
