/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PriceListItemDto {
  durationMinutes?: number;

  /**
   * The default range's starting price; absent only when the job has no default range
   */
  fromBani?: number;
  jobTypeId: string;
  nameEn: string;
  nameRo: string;

  /**
   * Drivers see the job on the garage profile
   */
  public: boolean;

  /**
   * Only when the job is not public: the first that applies, in this order
   */
  reason?: 'rejected' | 'awaiting_approval' | 'not_authorised' | 'hidden_by_garage' | 'no_top_price';

  /**
   * The default range's top price, when set
   */
  toBani?: number;
}
