/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProfileViewDto {

  /**
   * Where the visitor came from; anything else is profile_direct
   */
  source?: 'search' | 'map' | 'home' | 'shared_link' | 'saved' | 'profile_direct';
}
