/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProvidersDto {

  /**
   * Sign-in with Apple is configured
   */
  apple: boolean;

  /**
   * Sign-in with Google is configured
   */
  google: boolean;
}
