/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicGarageBrandDto {
  id: string;
  name: string;
  slug: string;

  /**
   * does_not_take also when the garage never named the brand
   */
  stance: 'works_on' | 'does_not_take';
}
