/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BrandRefDto } from '../models/brand-ref-dto';
import { PublicGarageBrandDto } from '../models/public-garage-brand-dto';
export interface PublicGarageDto {

  /**
   * A workshop only.
   */
  address?: string;

  /**
   * Only when the read named a catalogue brand
   */
  brand?: PublicGarageBrandDto;
  brandNote: string | null;
  businessKind?: 'company' | 'pfa' | 'ii' | 'mobile';

  /**
   * The line the garage wrote about itself, as written
   */
  description?: string;
  doesNotTake: Array<BrandRefDto>;
  id: string;

  /**
   * A workshop only.
   */
  latitude?: number;

  /**
   * A workshop only.
   */
  longitude?: number;
  name: string;

  /**
   * Out of 5, one decimal; null until reviews exist
   */
  rating: number | null;
  refusalPhrase: string | null;
  reviewCount: number;

  /**
   * A mobile mechanic only: how far from its base it travels.
   */
  serviceRadiusKm?: number;
  slug: string;

  /**
   * When MotorFix last verified the garage
   */
  verifiedAt: string | null;
  worksOn: Array<BrandRefDto>;
}
