/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BrandRefDto } from '../models/brand-ref-dto';
export interface PublicGarageDto {

  /**
   * A workshop only.
   */
  address?: string;
  brandNote: string | null;
  doesNotTake: Array<BrandRefDto>;
  id: string;

  /**
   * A workshop only.
   */
  latitude?: number;

  /**
   * A workshop only.
   */
  longitude?: number;
  name: string;
  refusalPhrase: string | null;

  /**
   * A mobile mechanic only: how far from its base it travels.
   */
  serviceRadiusKm?: number;
  slug: string;
  worksOn: Array<BrandRefDto>;
}
