/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicGaragePhotoDto {

  /**
   * The display copy (1,600 px), signed for an hour
   */
  displayUrl: string;

  /**
   * Upright, when known
   */
  height?: number;
  id: string;

  /**
   * The thumbnail copy (400 px), signed for an hour
   */
  thumbnailUrl: string;

  /**
   * Upright, when known
   */
  width?: number;
}
