/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicBrandDto {
  fuels: Array<'petrol' | 'diesel' | 'hybrid' | 'electric'>;
  id: string;
  name: string;
  slug: string;
}
