/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PushKeysDto {

  /**
   * The browser’s auth secret (base64url)
   */
  auth: string;

  /**
   * The browser’s public key (base64url)
   */
  p256dh: string;
}
