/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PushKeyDto {

  /**
   * The server’s VAPID public key; null when push is off
   */
  publicKey: string | null;
}
