/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GarageRefDto } from '../models/garage-ref-dto';
export interface RecipientDto {
  answeredAt: string | null;
  createdAt: string;
  garage: GarageRefDto;
  id: string;
  status: 'waiting' | 'quoted' | 'declined' | 'expired' | 'closed';
}
