/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RecordConsentDto {

  /**
   * When the choice was made, by the browser; at most 5 minutes ahead of the server
   */
  at: string;

  /**
   * Made once by the browser
   */
  browserConsentId: string;
  decision: 'granted' | 'refused' | 'withdrawn';
  language: 'ro' | 'en';

  /**
   * The text the choice was made under; only the current one
   */
  textVersion: string;
}
