/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RecordVerificationCheckDto {

  /**
   * RAR activity codes the authorisation covers; activities kind only, required when ok
   */
  activities?: Array<string>;

  /**
   * Trimmed; required for warning and failed; replaces the stored detail
   */
  detail?: string;
  result: 'ok' | 'warning' | 'failed';
}
