/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RefreshDto {

  /**
   * The role the tab is showing; used when the account still holds it
   */
  role?: 'driver' | 'garage' | 'receptionist' | 'mechanic' | 'admin';
}
