/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReorderJobStepsDto {

  /**
   * Every step of the job, once each, in the new order
   */
  stepIds: Array<string>;
}
