/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GarageBrandStanceDto } from '../models/garage-brand-stance-dto';
export interface ReplaceGarageBrandsDto {

  /**
   * Trimmed; blank or left out is no note
   */
  brandNote?: string;

  /**
   * Every marked brand once; a brand left out is switched off
   */
  brands: Array<GarageBrandStanceDto>;

  /**
   * Trimmed; blank or left out is no phrase
   */
  refusalPhrase?: string;
}
