/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BookingDto } from '../models/booking-dto';
import { CarSnapshotDto } from '../models/car-snapshot-dto';
import { QuoteDto } from '../models/quote-dto';
import { RecipientDto } from '../models/recipient-dto';
import { RequestJobDto } from '../models/request-job-dto';
export interface RequestDto {
  booking: (BookingDto & {
}) | null;
  car: CarSnapshotDto;
  closedAt: string | null;
  closedReason: ('expired' | 'cancelled' | 'booking_lapsed' | 'booking_cancelled' | 'no_show' | 'account_closed') | null;
  createdAt: string;

  /**
   * As the driver wrote it; the list shows its first line when there is no job
   */
  description: string | null;
  expiresAt: string;
  id: string;
  jobs: Array<RequestJobDto>;
  quotes: Array<QuoteDto>;
  quotesCount: number;
  recipients: Array<RecipientDto>;
  status: 'sent' | 'quoted' | 'booked' | 'in_work' | 'done' | 'closed';
}
