/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RequestSummaryDto } from '../models/request-summary-dto';
export interface RequestListDto {
  items: Array<RequestSummaryDto>;
  nextCursor: string | null;
  total: number;
}
