/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CarSnapshotDto } from '../models/car-snapshot-dto';
import { RequestJobDto } from '../models/request-job-dto';
export interface RequestSummaryDto {
  car: CarSnapshotDto;
  closedAt: string | null;
  closedReason: ('expired' | 'cancelled' | 'booking_lapsed' | 'booking_cancelled' | 'no_show' | 'account_closed') | null;
  createdAt: string;
  expiresAt: string;
  id: string;
  jobs: Array<RequestJobDto>;
  quotesCount: number;
  status: 'sent' | 'quoted' | 'booked' | 'in_work' | 'done' | 'closed';
}
