/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RequestJobDto {
  id: string;
  jobTypeId: string;
  nameEn: string;
  nameRo: string;
  position: number;
}
