/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResponseRateDto {

  /**
   * Percent answered within a day; only in the rate state
   */
  rate?: number;

  /**
   * new: under 10 requests ever; none: no request counted in 30 days
   */
  state: 'new' | 'rate' | 'none';
}
