/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PushKeysDto } from '../models/push-keys-dto';
export interface SavePushSubscriptionDto {

  /**
   * The push service address of the browser
   */
  endpoint: string;
  keys: PushKeysDto;

  /**
   * The browser’s own description
   */
  label?: string;
}
