/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NewsTextDto } from '../models/news-text-dto';
export interface SendNewsDto {

  /**
   * The text, in both languages
   */
  text: NewsTextDto;

  /**
   * The subject, in both languages
   */
  title: NewsTextDto;
}
