/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SendQuoteDto {
  durationMinutes: number;
  fromLei: number;

  /**
   * Whitespace alone is no note
   */
  note?: string | null;
  requestId: string;

  /**
   * The proposed start, with its offset; later than now
   */
  slot: string;
  toLei: number;
}
