/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SignUpDto {

  /**
   * Trimmed; stored and compared in lower case
   */
  email: string;

  /**
   * The interface language
   */
  language: 'ro' | 'en';

  /**
   * Trimmed
   */
  name: string;

  /**
   * 8 to 128 characters, not a common password
   */
  password: string;
}
