/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SignInDto {

  /**
   * Trimmed; compared without letter case
   */
  email: string;
  password: string;

  /**
   * Keep the session after the browser closes
   */
  remember?: boolean;
}
