/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ConsentDto } from '../models/consent-dto';
export interface SignUpDto {

  /**
   * The current terms and privacy versions; without them the answer is 400 consent_required
   */
  consent?: ConsentDto;

  /**
   * Trimmed; stored and compared in lower case
   */
  email: string;

  /**
   * The interface language
   */
  language: 'ro' | 'en';

  /**
   * Trimmed
   */
  name: string;

  /**
   * 8 to 128 characters, not a common password
   */
  password: string;
}
