/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StaffChannelDto } from '../models/staff-channel-dto';
export interface StaffNotificationTypeDto {

  /**
   * Empty for a type that is shown in the app only
   */
  channels: Array<StaffChannelDto>;

  /**
   * A notification type, e.g. REQUEST_RECEIVED
   */
  type: string;
}
