/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StaffSectionDto } from '../models/staff-section-dto';
import { StaffWhatsAppDto } from '../models/staff-whats-app-dto';
export interface StaffNotificationsDto {

  /**
   * Null for the admin list
   */
  garageId: string | null;
  garageName: string | null;
  role: 'owner' | 'receptionist' | 'mechanic' | 'admin';
  sections: Array<StaffSectionDto>;
  whatsapp: StaffWhatsAppDto;
}
