/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StaffInviteSentDto {

  /**
   * False when the e-mail could not be sent
   */
  emailSent: boolean;
  id: string;

  /**
   * The invite link, only when the e-mail could not be sent, for the owner to pass on
   */
  link?: string;
}
