/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StaffInviteDto {
  canAnswerQuotes?: {
};
  canMoveBookings?: {
};
  canRecordFinalPrice?: {
};

  /**
   * Trimmed; stored and compared in lower case
   */
  email: string;
  kind: 'mechanic' | 'receptionist';

  /**
   * Trimmed
   */
  name: string;
}
