/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StaffChannelDto {
  channel: 'email' | 'push' | 'whatsapp';

  /**
   * Whether the message goes by this channel
   */
  enabled: boolean;

  /**
   * Always on: it cannot be switched off
   */
  locked: boolean;
}
