/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StaffNotificationTypeDto } from '../models/staff-notification-type-dto';
export interface StaffSectionDto {
  key: 'requests_quotes' | 'bookings' | 'reviews' | 'account' | 'admin';
  types: Array<StaffNotificationTypeDto>;
}
