/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SwitchRoleDto {

  /**
   * One of the roles the account holds
   */
  role: 'driver' | 'garage' | 'receptionist' | 'mechanic' | 'admin';
}
