/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CourtesyCarDto } from '../models/courtesy-car-dto';
import { PaymentMethodsDto } from '../models/payment-methods-dto';
export interface UpdateGarageDto {

  /**
   * Only for a garage that lists the courtesy car
   */
  courtesyCar?: CourtesyCarDto;

  /**
   * All three; at least one true
   */
  paymentMethods?: PaymentMethodsDto;
}
