/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateNotificationGroupDto {
  enabled: boolean;
  key: 'offers' | 'bookings' | 'due_dates' | 'news' | 'reviews_history';
}
