/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateMeDto {

  /**
   * Trimmed; null or blank saves no city
   */
  city?: string | null;
  language?: 'ro' | 'en';

  /**
   * Trimmed
   */
  name?: string;
}
