/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CheckSummaryDto } from '../models/check-summary-dto';
import { VerificationCheckDto } from '../models/verification-check-dto';
export interface VerificationCheckRecordedDto {
  check: VerificationCheckDto;

  /**
   * The garage's RAR activity codes after the save
   */
  rarActivities: Array<string>;
  summary: CheckSummaryDto;
}
