/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VerificationCheckDto {

  /**
   * False until automatic look-ups exist
   */
  automatic: boolean;
  detail: string | null;
  id: string;
  kind: 'company' | 'caen' | 'rar' | 'activities' | 'representative' | 'address' | 'photos' | 'documents';
  recordedAt: string | null;
  recordedBy: string | null;
  result: 'not_run' | 'ok' | 'warning' | 'failed';
}
