/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UnreadCountDto } from '../../models/unread-count-dto';

export interface BellControllerUnreadCount$Params {
}

export function bellControllerUnreadCount(http: HttpClient, rootUrl: string, params?: BellControllerUnreadCount$Params, context?: HttpContext): Observable<StrictHttpResponse<UnreadCountDto>> {
  const rb = new RequestBuilder(rootUrl, bellControllerUnreadCount.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UnreadCountDto>;
    })
  );
}

bellControllerUnreadCount.PATH = '/api/v1/notifications/unread-count';
