/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationPageDto } from '../../models/notification-page-dto';

export interface BellControllerList$Params {

/**
 * The last item of the previous page
 */
  cursor?: string;

/**
 * The texts' language; the account's when left out
 */
  language?: 'ro' | 'en';
}

export function bellControllerList(http: HttpClient, rootUrl: string, params?: BellControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationPageDto>> {
  const rb = new RequestBuilder(rootUrl, bellControllerList.PATH, 'get');
  if (params) {
    rb.query('cursor', params.cursor, {});
    rb.query('language', params.language, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationPageDto>;
    })
  );
}

bellControllerList.PATH = '/api/v1/notifications';
