/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NewsSentDto } from '../../models/news-sent-dto';
import { SendNewsDto } from '../../models/send-news-dto';

export interface NewsControllerSend$Params {
      body: SendNewsDto
}

export function newsControllerSend(http: HttpClient, rootUrl: string, params: NewsControllerSend$Params, context?: HttpContext): Observable<StrictHttpResponse<NewsSentDto>> {
  const rb = new RequestBuilder(rootUrl, newsControllerSend.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NewsSentDto>;
    })
  );
}

newsControllerSend.PATH = '/api/v1/admin/news';
