/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationPreferencesDto } from '../../models/notification-preferences-dto';

export interface NotificationPreferencesControllerRead$Params {
}

export function notificationPreferencesControllerRead(http: HttpClient, rootUrl: string, params?: NotificationPreferencesControllerRead$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationPreferencesDto>> {
  const rb = new RequestBuilder(rootUrl, notificationPreferencesControllerRead.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationPreferencesDto>;
    })
  );
}

notificationPreferencesControllerRead.PATH = '/api/v1/notification-preferences';
