/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationPreferencesDto } from '../../models/notification-preferences-dto';
import { UpdateNotificationPreferencesDto } from '../../models/update-notification-preferences-dto';

export interface NotificationPreferencesControllerSave$Params {
      body: UpdateNotificationPreferencesDto
}

export function notificationPreferencesControllerSave(http: HttpClient, rootUrl: string, params: NotificationPreferencesControllerSave$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationPreferencesDto>> {
  const rb = new RequestBuilder(rootUrl, notificationPreferencesControllerSave.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationPreferencesDto>;
    })
  );
}

notificationPreferencesControllerSave.PATH = '/api/v1/notification-preferences';
