/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TestMessageDto } from '../../models/test-message-dto';
import { TestMessageQueuedDto } from '../../models/test-message-queued-dto';

export interface NotificationsControllerTest$Params {
      body: TestMessageDto
}

export function notificationsControllerTest(http: HttpClient, rootUrl: string, params: NotificationsControllerTest$Params, context?: HttpContext): Observable<StrictHttpResponse<TestMessageQueuedDto>> {
  const rb = new RequestBuilder(rootUrl, notificationsControllerTest.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TestMessageQueuedDto>;
    })
  );
}

notificationsControllerTest.PATH = '/api/v1/admin/notifications/test';
