/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PushKeyDto } from '../../models/push-key-dto';

export interface PushSubscriptionsControllerKey$Params {
}

export function pushSubscriptionsControllerKey(http: HttpClient, rootUrl: string, params?: PushSubscriptionsControllerKey$Params, context?: HttpContext): Observable<StrictHttpResponse<PushKeyDto>> {
  const rb = new RequestBuilder(rootUrl, pushSubscriptionsControllerKey.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PushKeyDto>;
    })
  );
}

pushSubscriptionsControllerKey.PATH = '/api/v1/push-subscriptions/key';
