/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PushTestQueuedDto } from '../../models/push-test-queued-dto';

export interface PushSubscriptionsControllerTest$Params {
}

export function pushSubscriptionsControllerTest(http: HttpClient, rootUrl: string, params?: PushSubscriptionsControllerTest$Params, context?: HttpContext): Observable<StrictHttpResponse<PushTestQueuedDto>> {
  const rb = new RequestBuilder(rootUrl, pushSubscriptionsControllerTest.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PushTestQueuedDto>;
    })
  );
}

pushSubscriptionsControllerTest.PATH = '/api/v1/push-subscriptions/test';
