/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PushSubscriptionDto } from '../../models/push-subscription-dto';
import { SavePushSubscriptionDto } from '../../models/save-push-subscription-dto';

export interface PushSubscriptionsControllerSave$Params {
      body: SavePushSubscriptionDto
}

export function pushSubscriptionsControllerSave(http: HttpClient, rootUrl: string, params: PushSubscriptionsControllerSave$Params, context?: HttpContext): Observable<StrictHttpResponse<PushSubscriptionDto>> {
  const rb = new RequestBuilder(rootUrl, pushSubscriptionsControllerSave.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PushSubscriptionDto>;
    })
  );
}

pushSubscriptionsControllerSave.PATH = '/api/v1/push-subscriptions';
